-- Колода «Выше среднего B2» в общей базе слов. Напечатано vocabulario/deck2sql.py
-- Источник: vocabulario/baralho-completo-B2.json, карточек: 497.
-- Без темы (398): a habitação, satisfazer, elevado, a etapa, o nativo, a troça, ajustar, coerente, concreto, o destaque, o destinatário, a evolução, fluentemente, isolado, a serra, o acento, agitar, contestar, expor, implicar, o índice, o lazer, a negociação, a proximidade, recorrer, relatar, a repetição, a substituição, a tendência, o trajeto, tranquilizar, abordar, acusar, a admiração, o anexo, a angústia, autorizar, a beira-mar, o calão, a camada …
-- Повторное выполнение безопасно: содержимое обновляется, прогресс людей не трогается.

begin;

insert into public.pt_decks (id, name, descr, level_from, level_to, sort)
values ('b2', 'Выше среднего B2', '497 карточек уровня B2 с примерами и заметками', 'B2', 'B2', 40)
on conflict (id) do update set name = excluded.name, descr = excluded.descr,
  level_from = excluded.level_from, level_to = excluded.level_to, sort = excluded.sort;

insert into public.pt_words (id, deck_id, word, pos, ru, ex, exru, note, level, tema, sort) values
('w:habitação','b2','a habitação','сущ.','жильё','O preço da habitação subiu imenso em Lisboa.','Цены на жильё в Лиссабоне сильно выросли.','','B2','',0),
('w:satisfazer','b2','satisfazer','глаг.','удовлетворять','A resposta não satisfez ninguém na sala.','Ответ никого в зале не удовлетворил.','','B2','',1),
('w:elevado','b2','elevado','прил.','высокий (о величине)','O custo elevado das obras assustou os donos.','Высокая стоимость работ напугала владельцев.','','B2','',2),
('w:etapa','b2','a etapa','сущ.','этап','A obra está na última etapa e acaba em março.','Стройка на последнем этапе и закончится в марте.','','B2','',3),
('w:nativo','b2','o nativo','сущ.','носитель языка; местный житель','Prefiro aprender com um nativo do Porto.','Я предпочитаю учиться у носителя языка из Порту.','','B2','',4),
('w:troça','b2','a troça','сущ.','насмешка','Fizeram troça do sotaque dele durante todo o almoço.','Над его акцентом посмеивались весь обед.','fazer troça de — подшучивать','B2','',5),
('w:ajustar','b2','ajustar','глаг.','подгонять, регулировать','Preciso de ajustar o cinto da mochila.','Мне нужно отрегулировать ремень рюкзака.','','B2','',6),
('w:coerente','b2','coerente','прил.','последовательный, связный','O texto está bem escrito e coerente.','Текст хорошо написан и связен.','','B2','',7),
('w:concreto','b2','concreto','прил.','конкретный','Dê-me um exemplo concreto do problema que encontrou.','Приведите конкретный пример проблемы, с которой вы столкнулись.','','B2','',8),
('w:destaque','b2','o destaque','сущ.','акцент, выделение','A notícia teve destaque em todos os jornais.','Новость была на видном месте во всех газетах.','em destaque — на видном месте','B2','',9),
('w:destinatário','b2','o destinatário','сущ.','адресат, получатель','Escreva o nome do destinatário no envelope.','Напишите имя получателя на конверте.','','B2','',10),
('w:evolução','b2','a evolução','сущ.','развитие, эволюция','A evolução do doente tem sido positiva.','Состояние больного развивается положительно.','','B2','',11),
('w:fluentemente','b2','fluentemente','нареч.','бегло, свободно','Ela fala francês fluentemente desde criança, aprendeu em casa.','Она с детства свободно говорит по-французски — выучила дома.','','B2','',12),
('w:isolado','b2','isolado','прил.','изолированный, уединённый','A casa fica isolada, a três quilómetros da aldeia.','Дом стоит на отшибе, в трёх километрах от деревни.','','B2','',13),
('w:serra','b2','a serra','сущ.','горная гряда; пила','Passámos o fim de semana na Serra da Estrela.','Мы провели выходные в Серра-да-Эштрела.','То же слово значит «пила»','B2','',14),
('w:acento','b2','o acento','сущ.','ударение; диакритический знак','Esta palavra leva acento na última sílaba.','В этом слове ударение на последнем слоге.','Не путать с assento — сиденье','B2','',15),
('w:agitar','b2','agitar','глаг.','взбалтывать, встряхивать','Agite bem o frasco antes de usar.','Хорошо взболтайте флакон перед применением.','','B2','',16),
('w:contestar','b2','contestar','глаг.','оспаривать','Vários moradores contestaram a decisão da câmara.','Несколько жильцов оспорили решение мэрии.','','B2','',17),
('w:expor','b2','expor','глаг.','выставлять; излагать','O artista vai expor as suas obras em outubro.','Художник выставит свои работы в октябре.','','B2','',18),
('w:implicar','b2','implicar','глаг.','влечь за собой; придираться','Mudar de casa implica muitas despesas e muita paciência.','Переезд влечёт за собой много расходов и требует терпения.','implicar com alguém — цепляться к кому-то','B2','',19),
('w:índice','b2','o índice','сущ.','показатель; оглавление','O índice de desemprego desceu ligeiramente no último trimestre.','Уровень безработицы немного снизился в последнем квартале.','','B2','',20),
('w:lazer','b2','o lazer','сущ.','досуг','O centro tem várias atividades de lazer.','В центре есть разные виды досуга.','','B2','',21),
('w:negociação','b2','a negociação','сущ.','переговоры','As negociações duraram toda a madrugada e não deram nada.','Переговоры тянулись всю ночь и ничем не кончились.','','B2','',22),
('w:proximidade','b2','a proximidade','сущ.','близость','Escolhemos a casa pela proximidade da escola.','Мы выбрали дом из-за близости школы.','','B2','',23),
('w:recorrer','b2','recorrer','глаг.','прибегать; обжаловать','Tive de recorrer à ajuda dos vizinhos.','Мне пришлось прибегнуть к помощи соседей.','recorrer a','B2','',24),
('w:relatar','b2','relatar','глаг.','излагать, рассказывать','O jornalista relatou tudo com muito pormenor.','Журналист изложил всё очень подробно.','','B2','',25),
('w:repetição','b2','a repetição','сущ.','повторение','A repetição ajuda a fixar o vocabulário novo.','Повторение помогает закрепить новую лексику.','','B2','',26),
('w:substituição','b2','a substituição','сущ.','замена','A substituição das janelas custou dois mil euros.','Замена окон обошлась в две тысячи евро.','','B2','',27),
('w:tendência','b2','a tendência','сущ.','тенденция, склонность','Há uma tendência para preços mais altos.','Есть тенденция к росту цен.','','B2','',28),
('w:trajeto','b2','o trajeto','сущ.','путь, дорога (поездка)','O trajeto de casa ao trabalho demora meia hora.','Дорога от дома до работы занимает полчаса.','','B2','',29),
('w:tranquilizar','b2','tranquilizar','глаг.','успокаивать','O médico tranquilizou-nos logo na primeira consulta.','Врач успокоил нас уже на первом приёме.','','B2','',30),
('w:abordar','b2','abordar','глаг.','затрагивать (тему); подходить','O professor abordou um tema difícil hoje.','Преподаватель затронул сегодня сложную тему.','','B2','',31),
('w:acusar','b2','acusar','глаг.','обвинять','Acusaram-no de falsificar as contas da empresa.','Его обвинили в подделке отчётности компании.','','B2','',32),
('w:admiração','b2','a admiração','сущ.','восхищение','Sinto grande admiração pelo trabalho dela com as crianças.','Я очень восхищаюсь её работой с детьми.','','B2','',33),
('w:anexo','b2','o anexo','сущ.','приложение (к письму); пристройка','Envio o contrato em anexo neste email.','Отправляю договор в приложении к этому письму.','em anexo — во вложении','B2','',34),
('w:angústia','b2','a angústia','сущ.','тоска, тревога','Sentiu uma angústia estranha ao entrar na casa vazia.','Он ощутил странную тоску, войдя в пустой дом.','','B2','',35),
('w:autorizar','b2','autorizar','глаг.','разрешать, уполномочивать','O médico autorizou-o a voltar ao trabalho.','Врач разрешил ему вернуться к работе.','','B2','',36),
('w:beira-mar','b2','a beira-mar','сущ.','берег моря','Alugámos uma casa à beira-mar em agosto.','Мы сняли дом у моря в августе.','à beira-mar — на берегу','B2','',37),
('w:calão','b2','o calão','сущ.','сленг, жаргон','Ele usa muito calão quando fala com os amigos.','Он много говорит на сленге с друзьями.','Европейское слово для сленга','B2','',38),
('w:camada','b2','a camada','сущ.','слой','Aplique uma camada fina de creme na ferida.','Нанесите тонкий слой крема на рану.','','B2','',39),
('w:captar','b2','captar','глаг.','улавливать, воспринимать','O microfone não captou bem a voz dele.','Микрофон плохо уловил его голос.','','B2','',40),
('w:catedral','b2','a catedral','сущ.','кафедральный собор','A catedral de Braga é a mais antiga do país.','Собор в Браге — самый древний в стране.','','B2','',41),
('w:cerâmica','b2','a cerâmica','сущ.','керамика','Comprei uma peça de cerâmica em Caldas da Rainha.','Я купил керамику в Калдаш-да-Раинья.','','B2','',42),
('w:colaboração','b2','a colaboração','сущ.','сотрудничество','O projeto nasceu da colaboração entre duas escolas.','Проект родился из сотрудничества двух школ.','','B2','',43),
('w:compensação','b2','a compensação','сущ.','компенсация, возмещение','A companhia pagou uma compensação pelo atraso.','Компания выплатила компенсацию за задержку.','','B2','',44),
('w:competente','b2','competente','прил.','компетентный','É uma advogada competente e muito séria.','Она компетентный и очень серьёзный юрист.','','B2','',45),
('w:composição','b2','a composição','сущ.','состав; сочинение','Leia a composição do produto antes de comprar.','Прочитайте состав продукта перед покупкой.','','B2','',46),
('w:conceito','b2','o conceito','сущ.','понятие, концепция','Este conceito é difícil de explicar em poucas palavras.','Это понятие трудно объяснить в двух словах.','','B2','',47),
('w:contribuição','b2','a contribuição','сущ.','вклад','A contribuição dele foi decisiva para o resultado.','Его вклад был решающим для результата.','','B2','',48),
('w:desatar','b2','desatar','глаг.','развязывать; вдруг начать','A criança desatou a chorar no meio da loja.','Ребёнок вдруг расплакался посреди магазина.','desatar a + инфинитив — «вдруг начать»','B2','',49),
('w:desconfiança','b2','a desconfiança','сущ.','недоверие','Olhou para o vendedor com desconfiança e saiu da loja.','Он с недоверием посмотрел на продавца и вышел из магазина.','','B2','',50),
('w:desempenhar','b2','desempenhar','глаг.','исполнять (роль, функцию)','Ela desempenha um papel importante na equipa.','Она играет важную роль в команде.','','B2','',51),
('w:distinguir','b2','distinguir','глаг.','различать','É difícil distinguir os gémeos à distância.','Близнецов трудно различить издалека.','','B2','',52),
('w:elogiar','b2','elogiar','глаг.','хвалить','O chefe elogiou o trabalho de toda a equipa.','Начальник похвалил работу всей команды.','','B2','',53),
('w:empenho','b2','o empenho','сущ.','усердие, старание','Notou-se o empenho dela na preparação da festa.','Было видно её старание в подготовке праздника.','','B2','',54),
('w:escritura','b2','a escritura','сущ.','нотариальный акт (о недвижимости)','A escritura da casa é assinada na sexta-feira.','Акт купли-продажи дома подписывают в пятницу.','','B2','',55),
('w:estabilidade','b2','a estabilidade','сущ.','устойчивость, стабильность','Procuro um emprego com mais estabilidade e horário fixo.','Я ищу работу постабильнее и с фиксированным графиком.','','B2','',56),
('w:faixa','b2','a faixa','сущ.','полоса; дорожка (в альбоме)','Circule pela faixa da direita até à saída.','Двигайтесь по правой полосе до съезда.','','B2','',57),
('w:falésia','b2','a falésia','сущ.','скалистый обрыв, утёс','As falésias do Algarve são impressionantes ao pôr do sol.','Скалы Алгарви впечатляют на закате.','','B2','',58),
('w:felicitar','b2','felicitar','глаг.','поздравлять','Quero felicitá-lo pelo excelente resultado do seu trabalho.','Хочу поздравить вас с отличным результатом вашей работы.','Официальнее, чем dar os parabéns','B2','',59),
('w:herdade','b2','a herdade','сущ.','поместье, усадьба','Passámos a noite numa herdade alentejana rodeada de sobreiros.','Мы переночевали в усадьбе в Алентежу среди пробковых дубов.','','B2','',60),
('w:hesitar','b2','hesitar','глаг.','колебаться','Hesitei muito antes de aceitar o convite.','Я долго колебался, прежде чем принять приглашение.','','B2','',61),
('w:iluminar','b2','iluminar','глаг.','освещать','Umas velas iluminavam a sala toda durante o apagão.','Во время отключения света всю комнату освещали свечи.','','B2','',62),
('w:impresso','b2','o impresso','сущ.','бланк, формуляр','Preencha o impresso e entregue-o ao balcão.','Заполните бланк и сдайте его в окошко.','','B2','',63),
('w:incerteza','b2','a incerteza','сущ.','неопределённость','Vivemos meses de grande incerteza económica depois da crise.','После кризиса мы прожили месяцы большой экономической неопределённости.','','B2','',64),
('w:indiferença','b2','a indiferença','сущ.','безразличие','Respondeu com uma indiferença que me magoou.','Он ответил с безразличием, которое меня задело.','','B2','',65),
('w:indignação','b2','a indignação','сущ.','возмущение','A notícia provocou indignação em toda a aldeia.','Новость вызвала возмущение во всей деревне.','','B2','',66),
('w:informática','b2','a informática','сущ.','информатика','Ele trabalha em informática há quinze anos.','Он работает в информатике пятнадцать лет.','','B2','',67),
('w:inicialmente','b2','inicialmente','нареч.','поначалу, изначально','Inicialmente parecia simples, mas complicou-se logo na primeira semana.','Поначалу казалось просто, но уже на первой неделе всё усложнилось.','','B2','',68),
('w:intervenção','b2','a intervenção','сущ.','вмешательство; выступление','A intervenção dos bombeiros evitou o pior.','Вмешательство пожарных предотвратило худшее.','','B2','',69),
('w:irritação','b2','a irritação','сущ.','раздражение','O creme provocou uma irritação na pele.','Крем вызвал раздражение на коже.','','B2','',70),
('w:lagoa','b2','a lagoa','сущ.','лагуна, небольшое озеро','Demos uma volta a pé à volta da lagoa.','Мы обошли лагуну пешком.','','B2','',71),
('w:município','b2','o município','сущ.','муниципалитет (орган власти)','O município investiu na recolha de lixo.','Муниципалитет вложился в вывоз мусора.','Территория того же деления — o concelho','B2','',72),
('w:patamar','b2','o patamar','сущ.','лестничная площадка; уровень','Deixei as sacas no patamar do segundo andar.','Я оставил сумки на площадке второго этажа.','','B2','',73),
('w:península','b2','a península','сущ.','полуостров','Portugal e Espanha ocupam a Península Ibérica.','Португалия и Испания занимают Пиренейский полуостров.','','B2','',74),
('w:pinheiro','b2','o pinheiro','сущ.','сосна','Há um bosque de pinheiros atrás da casa.','За домом сосновый лес.','','B2','',75),
('w:prever','b2','prever','глаг.','предвидеть, прогнозировать','Preveem chuva forte para o fim de semana.','На выходные прогнозируют сильный дождь.','','B2','',76),
('w:proceder','b2','proceder','глаг.','поступать; приступать','Vamos proceder à leitura do contrato antes de assinar.','Прежде чем подписывать, приступим к чтению договора.','','B2','',77),
('w:reforçar','b2','reforçar','глаг.','усиливать, укреплять','A câmara reforçou a segurança na praia.','Мэрия усилила безопасность на пляже.','','B2','',78),
('w:saudar','b2','saudar','глаг.','приветствовать','Saudou os convidados à entrada da sala.','Он приветствовал гостей у входа в зал.','','B2','',79),
('w:sossegar','b2','sossegar','глаг.','успокаиваться','Sossega, ainda temos tempo de sobra para apanhar o comboio.','Успокойся, у нас полно времени, чтобы успеть на поезд.','','B2','',80),
('w:travessa','b2','a travessa','сущ.','блюдо (посуда); переулок','Trouxe o peixe numa travessa de barro.','Она принесла рыбу на глиняном блюде.','','B2','',81),
('w:volume','b2','o volume','сущ.','громкость; объём','Baixa o volume da televisão, por favor.','Убавь громкость телевизора, пожалуйста.','','B2','',82),
('w:intervir','b2','intervir','глаг.','вмешиваться','O árbitro teve de intervir logo no início.','Судье пришлось вмешаться в самом начале.','','B2','',83),
('w:independência','b2','a independência','сущ.','независимость','A independência financeira deu-lhe liberdade para escolher o trabalho.','Финансовая независимость дала ей свободу выбирать работу.','','B2','',84),
('w:comprometer-se','b2','comprometer-se','глаг.','обязаться, взять на себя','Comprometeu-se a entregar o trabalho na segunda.','Он обязался сдать работу в понедельник.','','B2','',85),
('w:estabelecimento','b2','o estabelecimento','сущ.','заведение','Este estabelecimento fecha às oito da noite.','Это заведение закрывается в восемь вечера.','','B2','',86),
('w:funcionamento','b2','o funcionamento','сущ.','работа, режим работы','O horário de funcionamento está afixado na porta.','Часы работы вывешены на двери.','','B2','',87),
('w:significativo','b2','significativo','прил.','значительный','Houve uma melhoria significativa nos resultados deste trimestre.','В этом квартале результаты значительно улучшились.','','B2','',88),
('w:imigrante','b2','o imigrante','сущ.','иммигрант','Muitos imigrantes trabalham na construção civil e na restauração.','Многие иммигранты работают в строительстве и в общепите.','','B2','',89),
('w:todavia','b2','todavia','союз','однако, тем не менее','Estava cansado; todavia, continuou a trabalhar até de madrugada.','Он устал; тем не менее работал до самого рассвета.','Книжное; в речи чаще no entanto','B2','',90),
('w:abacate','b2','o abacate','сущ.','авокадо','Comprei dois abacates maduros no mercado da praça.','Я купил два спелых авокадо на рынке на площади.','','B2','',91),
('w:abono','b2','o abono','сущ.','пособие','Recebem abono de família por cada filho.','Они получают семейное пособие на каждого ребёнка.','','B2','',92),
('w:abre-latas','b2','o abre-latas','сущ.','консервный нож','Não encontro o abre-latas em lado nenhum.','Я нигде не могу найти консервный нож.','Европейская форма; бразильцы говорят abridor','B2','',93),
('w:abreviatura','b2','a abreviatura','сущ.','сокращение, аббревиатура','Escreva o nome completo, sem abreviaturas nem iniciais.','Напишите полное имя, без сокращений и инициалов.','','B2','',94),
('w:absorver','b2','absorver','глаг.','впитывать, поглощать','Este pano absorve muito bem a água.','Эта тряпка очень хорошо впитывает воду.','','B2','',95),
('w:aceso','b2','aceso','прил.','включённый, горящий','Deixaste a luz da cozinha acesa outra vez.','Ты снова оставил свет на кухне включённым.','Противоположное — apagado','B2','',96),
('w:acolher','b2','acolher','глаг.','принимать, привечать','A aldeia acolheu bem as famílias que chegaram.','Деревня хорошо приняла приехавшие семьи.','','B2','',97),
('w:aconchegante','b2','aconchegante','прил.','уютный','O café tem um ambiente aconchegante no inverno.','Зимой в кафе уютная атмосфера.','','B2','',98),
('w:acostumar-se','b2','acostumar-se','глаг.','привыкать','Já me acostumei a acordar às seis.','Я уже привык вставать в шесть.','acostumar-se a','B2','',99),
('w:acrescentar','b2','acrescentar','глаг.','добавлять','Acrescente uma pitada de sal no fim.','Добавьте щепотку соли в конце.','','B2','',100),
('w:adepto','b2','o adepto','сущ.','болельщик, сторонник','Os adeptos encheram o estádio duas horas antes.','Болельщики заполнили стадион за два часа.','','B2','',101),
('w:adoçante','b2','o adoçante','сущ.','подсластитель','Uso adoçante em vez de açúcar no café.','Я использую подсластитель вместо сахара в кофе.','','B2','',102),
('w:adolescência','b2','a adolescência','сущ.','отрочество, подростковый возраст','A adolescência dele foi bastante complicada, mudaram de país.','Отрочество у него было непростым: семья переехала в другую страну.','','B2','',103),
('w:afável','b2','afável','прил.','приветливый, любезный','O senhor da receção é sempre muito afável.','Мужчина на ресепшене всегда очень приветлив.','','B2','',104),
('w:afiar','b2','afiar','глаг.','точить','Preciso de afiar as facas da cozinha.','Мне нужно наточить кухонные ножи.','','B2','',105),
('w:afilhado','b2','o afilhado','сущ.','крестник','Levei o meu afilhado ao circo no domingo.','Я водил крестника в цирк в воскресенье.','','B2','',106),
('w:afinar','b2','afinar','глаг.','настраивать (инструмент)','O músico afinou a guitarra antes do concerto.','Музыкант настроил гитару перед концертом.','','B2','',107),
('w:agarrar-se','b2','agarrar-se','глаг.','хвататься, цепляться','Agarrou-se ao corrimão para não cair nas escadas molhadas.','Он ухватился за перила, чтобы не упасть на мокрой лестнице.','agarrar-se a','B2','',108),
('w:agredir','b2','agredir','глаг.','нападать, набрасываться','Foi agredido à saída do bar na madrugada.','На него напали у выхода из бара под утро.','','B2','',109),
('w:agridoce','b2','agridoce','прил.','кисло-сладкий','O molho agridoce combina bem com porco.','Кисло-сладкий соус хорошо идёт со свининой.','','B2','',110),
('w:aguardente','b2','a aguardente','сущ.','водка, крепкая настойка','Depois do jantar serviram aguardente de medronho.','После ужина подали настойку из земляничного дерева.','Медронью — типичный алгарвийский напиток','B2','',111),
('w:aipo','b2','o aipo','сущ.','сельдерей','A sopa leva cenoura, batata e aipo.','В суп идут морковь, картофель и сельдерей.','','B2','',112),
('w:ajeitar','b2','ajeitar','глаг.','поправлять, прилаживать','Ajeitou o cabelo antes de entrar na sala.','Она поправила волосы, прежде чем войти в зал.','','B2','',113),
('w:alarmante','b2','alarmante','прил.','тревожный, вызывающий тревогу','Os números da poluição são alarmantes este ano.','Показатели загрязнения в этом году тревожны.','','B2','',114),
('w:albergue','b2','o albergue','сущ.','хостел, приют','Dormimos num albergue barato perto da estação.','Мы переночевали в дешёвом хостеле у вокзала.','','B2','',115),
('w:alça','b2','a alça','сущ.','лямка, ручка (сумки)','A alça da mala partiu-se a meio da viagem.','Ручка сумки оторвалась посреди поездки.','','B2','',116),
('w:alecrim','b2','o alecrim','сущ.','розмарин','Pus alecrim e alho nas batatas assadas no forno.','Я добавил розмарин и чеснок к картошке, запечённой в духовке.','','B2','',117),
('w:alegar','b2','alegar','глаг.','ссылаться, заявлять','Alegou problemas de saúde para faltar ao trabalho.','Он сослался на проблемы со здоровьем, чтобы не выйти на работу.','','B2','',118),
('w:almôndega','b2','a almôndega','сущ.','фрикаделька','Fiz almôndegas com arroz para o jantar.','Я приготовил фрикадельки с рисом на ужин.','','B2','',119),
('w:amadurecer','b2','amadurecer','глаг.','созревать; взрослеть','Os tomates ainda precisam de amadurecer uns dias.','Помидорам нужно ещё несколько дней, чтобы дозреть.','','B2','',120),
('w:ambiental','b2','ambiental','прил.','природоохранный, экологический','A empresa fez um estudo de impacto ambiental.','Компания провела исследование воздействия на окружающую среду.','','B2','',121),
('w:ambíguo','b2','ambíguo','прил.','двусмысленный, неоднозначный','A resposta dele foi ambígua de propósito.','Его ответ был двусмысленным нарочно.','','B2','',122),
('w:amistoso','b2','amistoso','прил.','дружеский; товарищеский','Foi um jogo amistoso entre as duas escolas.','Это был товарищеский матч между двумя школами.','','B2','',123),
('w:amor-próprio','b2','o amor-próprio','сущ.','самолюбие','A crítica do chefe feriu-lhe o amor-próprio.','Замечание начальника задело его самолюбие.','','B2','',124),
('w:amuado','b2','amuado','прил.','надутый, обиженный','Ficou amuado o resto da tarde por causa da discussão.','Он дулся весь остаток дня из-за той ссоры.','','B2','',125),
('w:amuar','b2','amuar','глаг.','дуться, обижаться','Não amues só porque perdeste o jogo.','Не дуйся только потому, что проиграл.','Разговорное, чисто португальское','B2','',126),
('w:analfabeto','b2','analfabeto','прил.','неграмотный','Naquela altura, metade da aldeia era analfabeta.','В то время половина деревни была неграмотной.','','B2','',127),
('w:andorinha','b2','a andorinha','сущ.','ласточка','As andorinhas voltam para os telhados na primavera.','Ласточки возвращаются на крыши весной.','','B2','',128),
('w:anestésico','b2','o anestésico','сущ.','обезболивающее, анестетик','O dentista deu-me um anestésico local antes de arrancar o dente.','Стоматолог сделал местную анестезию, прежде чем удалить зуб.','','B2','',129),
('w:animação','b2','a animação','сущ.','оживление; анимация','Havia muita animação na praça durante as festas.','На площади во время праздников было очень оживлённо.','','B2','',130),
('w:anotação','b2','a anotação','сущ.','заметка, пометка','Fiz várias anotações à margem do livro.','Я сделал несколько пометок на полях книги.','','B2','',131),
('w:antebraço','b2','o antebraço','сущ.','предплечье','Partiu o antebraço a jogar futebol com os amigos.','Он сломал предплечье, играя в футбол с друзьями.','','B2','',132),
('w:antecipar','b2','antecipar','глаг.','переносить на более ранний срок; предвосхищать','Antecipámos a reunião para as nove por causa das viagens.','Мы перенесли совещание на девять из-за поездок.','','B2','',133),
('w:de antemão','b2','de antemão','нареч.','заранее, наперёд','Agradeço de antemão a sua atenção e a resposta rápida.','Заранее благодарю за внимание и быстрый ответ.','Устойчивый оборот','B2','',134),
('w:antepassado','b2','o antepassado','сущ.','предок','Os antepassados dele vieram dos Açores no século dezanove.','Его предки приехали с Азорских островов в девятнадцатом веке.','','B2','',135),
('w:apagar-se','b2','apagar-se','глаг.','гаснуть, выключаться','A luz apagou-se de repente em toda a rua.','Свет внезапно погас на всей улице.','','B2','',136),
('w:apaixonante','b2','apaixonante','прил.','затягивающий, влюбляющий в себя','O trabalho dela é difícil, mas apaixonante.','Её работа трудная, но увлекательная.','','B2','',137),
('w:aparentar','b2','aparentar','глаг.','выглядеть на, казаться','Ela aparenta menos idade do que tem.','Она выглядит моложе своих лет.','','B2','',138),
('w:apelar','b2','apelar','глаг.','взывать, призывать','A câmara apelou à poupança de água.','Мэрия призвала экономить воду.','apelar a','B2','',139),
('w:aperfeiçoar','b2','aperfeiçoar','глаг.','совершенствовать','Quero aperfeiçoar a minha pronúncia este ano.','В этом году я хочу улучшить своё произношение.','','B2','',140),
('w:apetitoso','b2','apetitoso','прил.','аппетитный','O cheiro que vem da cozinha está apetitoso.','Запах с кухни очень аппетитный.','','B2','',141),
('w:aplicado','b2','aplicado','прил.','прилежный, старательный','É uma aluna aplicada e muito curiosa.','Она прилежная и очень любознательная ученица.','','B2','',142),
('w:apontamento','b2','o apontamento','сущ.','конспект, запись','Tirei apontamentos durante toda a aula, mas não percebi tudo.','Я вёл конспект всё занятие, но не всё понял.','tirar apontamentos — конспектировать','B2','',143),
('w:apreensivo','b2','apreensivo','прил.','встревоженный, обеспокоенный','Estava apreensivo com o resultado dos exames.','Он был обеспокоен результатами анализов.','','B2','',144),
('w:arejar','b2','arejar','глаг.','проветривать','Deixa a roupa a arejar na varanda umas horas.','Оставь бельё проветриться на балконе на пару часов.','','B2','',145),
('w:armazenar','b2','armazenar','глаг.','хранить, складировать','Armazenamos a lenha na garagem para o inverno.','Мы храним дрова в гараже на зиму.','','B2','',146),
('w:arquitetura','b2','a arquitetura','сущ.','архитектура','A arquitetura da cidade velha é impressionante.','Архитектура старого города впечатляет.','','B2','',147),
('w:arrastar-se','b2','arrastar-se','глаг.','тащиться, тянуться','A reunião arrastou-se por mais de três horas.','Совещание растянулось больше чем на три часа.','','B2','',148),
('w:arrepiar','b2','arrepiar','глаг.','вызывать мурашки','Aquela história arrepia só de ouvir, ainda por cima é verdadeira.','От той истории мурашки бегут, а она к тому же правдивая.','','B2','',149),
('w:arrepio','b2','o arrepio','сущ.','мурашки, дрожь','Senti um arrepio quando ouvi aquele fado.','У меня побежали мурашки, когда я услышал то фаду.','','B2','',150),
('w:arrumação','b2','a arrumação','сущ.','уборка, наведение порядка','Fizemos uma grande arrumação na garagem no fim de semana.','На выходных мы устроили большую уборку в гараже.','','B2','',151),
('w:artesanal','b2','artesanal','прил.','ремесленный, ручной работы','Comprámos pão artesanal na feira do sábado.','Мы купили хлеб ручной выпечки на субботней ярмарке.','','B2','',152),
('w:artesanato','b2','o artesanato','сущ.','ремесло; изделия ручной работы','A loja vende artesanato de várias regiões.','Магазин продаёт изделия ручной работы из разных регионов.','','B2','',153),
('w:aspirar','b2','aspirar','глаг.','пылесосить; стремиться','Tenho de aspirar a casa antes das visitas.','Мне нужно пропылесосить дом до прихода гостей.','aspirar a — стремиться к','B2','',154),
('w:ata','b2','a ata','сущ.','протокол (собрания)','A ata da reunião foi enviada por email.','Протокол собрания разослали по электронной почте.','','B2','',155),
('w:atar','b2','atar','глаг.','завязывать','O miúdo já sabe atar os sapatos sozinho.','Мальчик уже умеет сам завязывать шнурки.','','B2','',156),
('w:atrair','b2','atrair','глаг.','привлекать','A feira do livro atraiu milhares de visitantes este ano.','Книжная ярмарка привлекла в этом году тысячи посетителей.','','B2','',157),
('w:atrapalhado','b2','atrapalhado','прил.','растерянный, неловкий','Ficou atrapalhado quando lhe fizeram a pergunta.','Он растерялся, когда ему задали вопрос.','','B2','',158),
('w:atrevimento','b2','o atrevimento','сущ.','дерзость, наглость','Teve o atrevimento de responder ao professor.','У него хватило дерзости огрызнуться преподавателю.','','B2','',159),
('w:atrito','b2','o atrito','сущ.','трение; трения, разлад','Houve alguns atritos entre os dois departamentos.','Между двумя отделами возникли трения.','','B2','',160),
('w:auscultador','b2','o auscultador','сущ.','наушник; телефонная трубка','Esqueci-me dos auscultadores em casa e a viagem foi longa.','Я забыл наушники дома, а дорога была долгой.','Европейское слово; во мн. ч. — наушники','B2','',161),
('w:auxílio','b2','o auxílio','сущ.','помощь, содействие','Pediu auxílio a um polícia na rua.','Он попросил помощи у полицейского на улице.','','B2','',162),
('w:avarento','b2','avarento','прил.','скупой','O tio dele é avarento até para si próprio.','Его дядя скуп даже по отношению к себе.','','B2','',163),
('w:avelã','b2','a avelã','сущ.','фундук','Este chocolate leva avelãs inteiras e um pouco de sal.','В этом шоколаде цельный фундук и немного соли.','','B2','',164),
('w:azarado','b2','azarado','прил.','невезучий','Ele é azarado, perde sempre a chave.','Он невезучий, вечно теряет ключ.','','B2','',165),
('w:azeitona','b2','a azeitona','сущ.','оливка','Trouxeram azeitonas e pão antes da refeição.','Перед едой принесли оливки и хлеб.','','B2','',166),
('w:azia','b2','a azia','сущ.','изжога','A comida picante dá-me azia durante a noite toda.','От острой еды у меня всю ночь изжога.','','B2','',167),
('w:balanço','b2','o balanço','сущ.','итог, подведение итогов; качели','No fim do ano fazemos sempre um balanço.','В конце года мы всегда подводим итоги.','fazer um balanço','B2','',168),
('w:barrar','b2','barrar','глаг.','намазывать; преграждать','Barrou o pão com manteiga e doce.','Он намазал хлеб маслом и вареньем.','','B2','',169),
('w:batedeira','b2','a batedeira','сущ.','миксер','Bata as claras com a batedeira durante cinco minutos.','Взбейте белки миксером в течение пяти минут.','','B2','',170),
('w:batizado','b2','o batizado','сущ.','крестины','O batizado da minha sobrinha é no sábado.','Крестины моей племянницы в субботу.','','B2','',171),
('w:beliscar','b2','beliscar','глаг.','щипать','O irmão beliscou-lhe o braço por brincadeira.','Брат ущипнул её за руку в шутку.','','B2','',172),
('w:bem-educado','b2','bem-educado','прил.','воспитанный','O filho deles é muito bem-educado à mesa.','Их сын очень воспитан за столом.','Противоположное — mal-educado','B2','',173),
('w:beringela','b2','a beringela','сущ.','баклажан','Assei beringelas com azeite, alho e um pouco de orégãos.','Я запёк баклажаны с оливковым маслом, чесноком и щепоткой орегано.','','B2','',174),
('w:berro','b2','o berro','сущ.','крик, вопль','Ouvimos um berro vindo do andar de cima.','Мы услышали крик сверху.','','B2','',175),
('w:beterraba','b2','a beterraba','сущ.','свёкла','A salada leva beterraba cozida e nozes.','В салат идут варёная свёкла и грецкие орехи.','','B2','',176),
('w:bicho','b2','o bicho','сущ.','зверушка; насекомое','Há um bicho estranho na parede da cozinha.','На стене кухни какое-то странное насекомое.','','B2','',177),
('w:birra','b2','a birra','сущ.','каприз, истерика','O miúdo fez uma birra enorme no supermercado.','Ребёнок закатил огромную истерику в супермаркете.','fazer birra — капризничать','B2','',178),
('w:biscate','b2','o biscate','сущ.','подработка, халтура','Faz uns biscates aos fins de semana.','Он подрабатывает по выходным.','','B2','',179),
('w:bronzear','b2','bronzear','глаг.','загорать','Ela bronzeia-se com muita facilidade, basta uma manhã de praia.','Она загорает очень легко — хватает одного утра на пляже.','','B2','',180),
('w:brusco','b2','brusco','прил.','резкий, внезапный','Houve uma descida brusca da temperatura durante a noite.','Ночью произошло резкое падение температуры.','','B2','',181),
('w:bule','b2','o bule','сущ.','заварочный чайник','Pôs o chá a repousar no bule uns minutos.','Он дал чаю настояться в чайнике пару минут.','','B2','',182),
('w:burlar','b2','burlar','глаг.','обманывать, мошенничать','Burlaram vários idosos com telefonemas falsos do banco.','Несколько пожилых людей обманули фальшивыми звонками из банка.','Мошенничество — a burla','B2','',183),
('w:buzinar','b2','buzinar','глаг.','сигналить','O carro de trás buzinou duas vezes.','Машина сзади дважды посигналила.','','B2','',184),
('w:cabide','b2','o cabide','сущ.','вешалка, плечики','Pendura o casaco naquele cabide, por favor.','Повесь куртку на ту вешалку, пожалуйста.','','B2','',185),
('w:caçarola','b2','a caçarola','сущ.','сотейник, глубокая кастрюля','Deixei a sopa a ferver na caçarola grande.','Я оставил суп кипеть в большой кастрюле.','','B2','',186),
('w:cálculo','b2','o cálculo','сущ.','расчёт, подсчёт','Fiz um cálculo rápido das despesas do mês.','Я быстро подсчитал расходы за месяц.','','B2','',187),
('w:caldo','b2','o caldo','сущ.','бульон, отвар','O caldo verde leva couve, batata e chouriço.','Калду верде готовят из капусты, картофеля и колбасы.','','B2','',188),
('w:caloroso','b2','caloroso','прил.','тёплый, радушный','Recebeu-nos com um abraço caloroso à porta de casa.','Он встретил нас тёплыми объятиями у порога.','','B2','',189),
('w:calvo','b2','calvo','прил.','лысый','Ficou calvo muito cedo, aos trinta anos.','Он облысел очень рано, в тридцать лет.','','B2','',190),
('w:camomila','b2','a camomila','сущ.','ромашка','Um chá de camomila ajuda a dormir.','Ромашковый чай помогает уснуть.','','B2','',191),
('w:candidatar-se','b2','candidatar-se','глаг.','подавать заявку, баллотироваться','Candidatou-se a uma bolsa de estudo em Coimbra.','Он подал заявку на стипендию в Коимбре.','candidatar-se a','B2','',192),
('w:candidato','b2','o candidato','сущ.','кандидат, соискатель','Havia trinta candidatos para uma única vaga.','На одно место было тридцать кандидатов.','','B2','',193),
('w:cansar','b2','cansar','глаг.','утомлять','Subir tantas escadas cansa qualquer pessoa, mesmo em boa forma.','Столько ступенек утомят кого угодно, даже в хорошей форме.','','B2','',194),
('w:cantarolar','b2','cantarolar','глаг.','напевать','Ia a cantarolar uma canção antiga pelo caminho.','Он шёл по дороге, напевая старую песню.','','B2','',195),
('w:capacho','b2','o capacho','сущ.','коврик у двери','Deixei a chave debaixo do capacho, como combinámos.','Я оставил ключ под ковриком, как договаривались.','','B2','',196),
('w:capela','b2','a capela','сущ.','часовня','Há uma capela pequena no alto do monte.','На вершине холма стоит маленькая часовня.','','B2','',197),
('w:caroço','b2','o caroço','сущ.','косточка (плода)','Cuidado com o caroço da azeitona, parte-se um dente.','Осторожно с оливковой косточкой — так и зуб сломать недолго.','','B2','',198),
('w:casca','b2','a casca','сущ.','кожура, скорлупа, корка','Descasque a laranja e guarde a casca.','Очистите апельсин и сохраните кожуру.','','B2','',199)
on conflict (id) do update set deck_id = excluded.deck_id, word = excluded.word,
  pos = excluded.pos, ru = excluded.ru, ex = excluded.ex, exru = excluded.exru,
  note = excluded.note, level = excluded.level, tema = excluded.tema, sort = excluded.sort;

insert into public.pt_words (id, deck_id, word, pos, ru, ex, exru, note, level, tema, sort) values
('w:cativante','b2','cativante','прил.','располагающий, обаятельный','Tem um sorriso cativante e uma voz calma.','У неё обаятельная улыбка и спокойный голос.','','B2','',200),
('w:católico','b2','o católico','сущ.','католик','A maioria dos portugueses é católica, embora poucos vão à missa.','Большинство португальцев — католики, хотя в церковь ходят немногие.','','B2','',201),
('w:cegonha','b2','a cegonha','сущ.','аист','As cegonhas fazem ninho nas chaminés antigas.','Аисты вьют гнёзда на старых трубах.','','B2','',202),
('w:censura','b2','a censura','сущ.','цензура; порицание','Durante a ditadura havia censura na imprensa.','Во время диктатуры в прессе была цензура.','','B2','',203),
('w:centeio','b2','o centeio','сущ.','рожь','Prefiro pão de centeio ao pão branco.','Я предпочитаю ржаной хлеб белому.','','B2','',204),
('w:cerne','b2','o cerne','сущ.','суть, ядро','Chegámos finalmente ao cerne da questão ao fim de duas horas.','Через два часа мы наконец добрались до сути вопроса.','','B2','',205),
('w:cervejaria','b2','a cervejaria','сущ.','пивной ресторан','Jantámos marisco numa cervejaria perto do Cais.','Мы поужинали морепродуктами в пивной у причала.','В Португалии это ещё и ресторан морепродуктов','B2','',206),
('w:chefiar','b2','chefiar','глаг.','возглавлять','Ela chefia o departamento há três anos.','Она возглавляет отдел уже три года.','','B2','',207),
('w:chinelo','b2','o chinelo','сущ.','тапок, шлёпанец','Anda de chinelos por casa o dia todo.','Он весь день ходит по дому в тапках.','','B2','',208),
('w:chocar','b2','chocar','глаг.','шокировать; сталкиваться','A notícia chocou toda a gente na aldeia.','Новость шокировала всех в деревне.','','B2','',209),
('w:chouriço','b2','o chouriço','сущ.','колбаса чурису','O cozido leva chouriço, couve e batata.','В кожиду идут чурису, капуста и картофель.','Копчёная свиная колбаса, основа многих блюд','B2','',210),
('w:chuvoso','b2','chuvoso','прил.','дождливый','O outono no Minho é bastante chuvoso.','Осень в Минью довольно дождливая.','','B2','',211),
('w:cicatrizar','b2','cicatrizar','глаг.','заживать','A ferida cicatrizou em pouco mais de uma semana.','Рана зажила чуть больше чем за неделю.','','B2','',212),
('w:ciclista','b2','o ciclista','сущ.','велосипедист','Os ciclistas têm uma faixa própria nesta avenida.','У велосипедистов на этом проспекте своя полоса.','','B2','',213),
('w:cidadania','b2','a cidadania','сущ.','гражданство','Pediu a cidadania portuguesa depois de cinco anos.','Он подал на португальское гражданство через пять лет.','','B2','',214),
('w:cigano','b2','o cigano','сущ.','цыган','Havia uma feira de ciganos à saída da vila.','На выезде из городка была цыганская ярмарка.','','B2','',215),
('w:circulação','b2','a circulação','сущ.','движение; кровообращение','A circulação está cortada na ponte até domingo.','Движение по мосту перекрыто до воскресенья.','','B2','',216),
('w:cláusula','b2','a cláusula','сущ.','пункт договора','Leia com atenção a cláusula sobre o depósito.','Внимательно прочитайте пункт о залоге.','','B2','',217),
('w:colaborador','b2','o colaborador','сущ.','сотрудник','A empresa tem cinquenta colaboradores em Lisboa.','В компании пятьдесят сотрудников в Лиссабоне.','','B2','',218),
('w:colcha','b2','a colcha','сущ.','покрывало','Pôs uma colcha grossa na cama por causa do frio.','Она постелила толстое покрывало из-за холода.','','B2','',219),
('w:colorido','b2','colorido','прил.','цветной, яркий','O mercado estava colorido e cheio de gente.','Рынок был ярким и полным людей.','','B2','',220),
('w:comemoração','b2','a comemoração','сущ.','празднование','Houve comemorações em toda a cidade nesse dia.','В тот день по всему городу были празднования.','','B2','',221),
('w:comentar','b2','comentar','глаг.','комментировать, высказываться','Prefiro não comentar o assunto por agora.','Пока я предпочту не комментировать этот вопрос.','','B2','',222),
('w:comerciante','b2','o comerciante','сущ.','торговец, коммерсант','Os comerciantes da rua pediram mais segurança.','Торговцы с этой улицы попросили усилить охрану.','','B2','',223),
('w:comodidade','b2','a comodidade','сущ.','удобство','O quarto é pequeno, mas tem todas as comodidades.','Номер маленький, но со всеми удобствами.','','B2','',224),
('w:comparecer','b2','comparecer','глаг.','являться, присутствовать','Tem de comparecer no tribunal na quinta-feira.','Вы должны явиться в суд в четверг.','','B2','',225),
('w:competitivo','b2','competitivo','прил.','конкурентный; соревновательный','O preço deles é muito competitivo para a qualidade oferecida.','Их цена очень выгодна для такого качества.','','B2','',226),
('w:complicação','b2','a complicação','сущ.','осложнение','Houve uma complicação depois da operação e ficou mais dias.','После операции возникло осложнение, и он пролежал дольше.','','B2','',227),
('w:compositor','b2','o compositor','сущ.','композитор','O compositor escreveu a música em duas semanas.','Композитор написал музыку за две недели.','','B2','',228),
('w:conceder','b2','conceder','глаг.','предоставлять, даровать','O banco concedeu-lhes um empréstimo a dez anos.','Банк предоставил им кредит на десять лет.','','B2','',229),
('w:concorrente','b2','o concorrente','сущ.','конкурент; участник конкурса','O nosso maior concorrente abriu loja ao lado.','Наш главный конкурент открыл магазин рядом.','','B2','',230),
('w:concorrer','b2','concorrer','глаг.','участвовать в конкурсе; конкурировать','Concorreu a uma vaga na universidade do Porto.','Он участвовал в конкурсе на место в университете Порту.','','B2','',231),
('w:concretizar','b2','concretizar','глаг.','осуществлять','Finalmente concretizámos o sonho de comprar casa.','Мы наконец осуществили мечту купить дом.','','B2','',232),
('w:condenar','b2','condenar','глаг.','осуждать, приговаривать','O tribunal condenou-o a dois anos de prisão.','Суд приговорил его к двум годам заключения.','','B2','',233),
('w:confeitaria','b2','a confeitaria','сущ.','лавка со сладостями','Comprámos os bolos naquela confeitaria antiga junto ao rio.','Мы купили пирожные в той старой лавке у реки.','Кофе и завтрак — скорее в pastelaria','B2','',234),
('w:conferir','b2','conferir','глаг.','сверять, проверять','Confira o troco antes de sair da loja.','Проверьте сдачу, прежде чем выйти из магазина.','','B2','',235),
('w:confidência','b2','a confidência','сущ.','доверительное признание','Fez-me uma confidência que prometi não contar a ninguém.','Он доверил мне тайну, которую я обещал никому не рассказывать.','Обычно во мн. ч.: fazer confidências a alguém','B2','',236),
('w:configuração','b2','a configuração','сущ.','настройка, наладка','A configuração do computador demorou mais do que esperávamos.','Настройка компьютера заняла больше времени, чем мы ожидали.','Настройки в телефоне — as definições, а не as configurações','B2','',237),
('w:configurar','b2','configurar','глаг.','настраивать','O técnico configurou a rede sem fios em dez minutos.','Мастер настроил беспроводную сеть за десять минут.','','B2','',238),
('w:confortar','b2','confortar','глаг.','утешать, ободрять','As palavras da avó confortaram-me naquele dia difícil.','Слова бабушки утешили меня в тот трудный день.','','B2','',239),
('w:confronto','b2','o confronto','сущ.','столкновение, противостояние','Houve um confronto entre adeptos à saída do estádio.','У выхода со стадиона произошло столкновение между болельщиками.','','B2','',240),
('w:confundir','b2','confundir','глаг.','путать, сбивать с толку','Confundo sempre estas duas palavras por causa do som.','Я всегда путаю эти два слова из-за звучания.','confundir-se — спутать одно с другим, обознаться','B2','',241),
('w:cônjuge','b2','o cônjuge','сущ.','супруг, супруга','O formulário pede também os dados do cônjuge.','В бланке нужно указать ещё и данные супруга.','Слово из документов; в речи — o marido, a mulher','B2','',242),
('w:conquista','b2','a conquista','сущ.','завоевание, достижение','O direito a férias pagas foi uma conquista importante.','Право на оплачиваемый отпуск стало важным завоеванием.','','B2','',243),
('w:consenso','b2','o consenso','сущ.','единое мнение, консенсус','Depois de muita discussão, chegámos finalmente a um consenso.','После долгого спора мы наконец пришли к общему мнению.','','B2','',244),
('w:conservação','b2','a conservação','сущ.','сохранение, сбережение','O museu gasta muito dinheiro na conservação dos quadros.','Музей тратит много денег на сохранение картин.','','B2','',245),
('w:conservador','b2','o conservador','сущ.','консерватор','Os conservadores votaram contra a mudança da lei.','Консерваторы проголосовали против изменения закона.','Как прилагательное — консервативный, осторожный','B2','',246),
('w:constituição','b2','a constituição','сущ.','конституция','A Constituição portuguesa garante o direito à saúde.','Португальская конституция гарантирует право на охрану здоровья.','Также состав, образование: a constituição de uma equipa','B2','',247),
('w:construtivo','b2','construtivo','прил.','конструктивный','A reunião foi curta, mas muito construtiva para todos.','Встреча была короткой, но очень конструктивной для всех.','','B2','',248),
('w:consumir','b2','consumir','глаг.','потреблять, расходовать','Este carro consome pouco combustível na cidade.','Эта машина мало расходует топлива в городе.','','B2','',249),
('w:consumo','b2','o consumo','сущ.','потребление, расход','O consumo de água aumentou muito durante o verão.','Потребление воды сильно выросло за лето.','','B2','',250),
('w:contágio','b2','o contágio','сущ.','заражение','A máscara reduz o risco de contágio nos transportes.','Маска снижает риск заражения в транспорте.','','B2','',251),
('w:contaminar','b2','contaminar','глаг.','загрязнять, заражать','A fábrica contaminou o rio durante muitos anos.','Завод загрязнял реку много лет.','','B2','',252),
('w:conter','b2','conter','глаг.','содержать, вмещать','Este produto contém leite e frutos secos.','Этот продукт содержит молоко и орехи.','Спрягается как ter: contenho, contém, contêm','B2','',253),
('w:continuação','b2','a continuação','сущ.','продолжение','A continuação da obra depende do dinheiro da câmara.','Продолжение работ зависит от денег муниципалитета.','Boa continuação! — пожелание хорошо провести остаток дня','B2','',254),
('w:contínuo','b2','contínuo','прил.','непрерывный, постоянный','O barulho contínuo das obras não me deixa dormir.','Непрерывный шум стройки не даёт мне спать.','','B2','',255),
('w:contradição','b2','a contradição','сущ.','противоречие','Há uma contradição evidente entre o que diz e faz.','Между его словами и делами явное противоречие.','','B2','',256),
('w:contradizer','b2','contradizer','глаг.','противоречить, возражать','Não gosto que me contradigam à frente dos outros.','Не люблю, когда мне возражают при других.','Спрягается как dizer: contradigo, contradiz','B2','',257),
('w:converter','b2','converter','глаг.','превращать, переделывать','Converteram o antigo convento num hotel de luxo.','Старый монастырь превратили в роскошный отель.','','B2','',258),
('w:conviver','b2','conviver','глаг.','уживаться, ладить','Aprendemos a conviver com os vizinhos do prédio.','Мы научились ладить с соседями по дому.','','B2','',259),
('w:convívio','b2','o convívio','сущ.','общение, дружеские посиделки','O convívio de Natal da empresa é sempre animado.','Рождественские посиделки в компании всегда проходят весело.','Так называют и саму встречу, и сам факт общения','B2','',260),
('w:convocar','b2','convocar','глаг.','созывать, вызывать','O treinador convocou os melhores jogadores para o jogo.','Тренер вызвал лучших игроков на матч.','','B2','',261),
('w:coordenar','b2','coordenar','глаг.','координировать, руководить','Ela coordena a equipa de enfermeiros do hospital.','Она руководит бригадой медсестёр в больнице.','','B2','',262),
('w:cordial','b2','cordial','прил.','сердечный, радушный','Recebeu-nos de forma cordial, apesar de não nos conhecer.','Он принял нас радушно, хотя и не был с нами знаком.','','B2','',263),
('w:costureira','b2','a costureira','сущ.','швея, портниха','Levei as calças à costureira para encurtar a bainha.','Я отнёс брюки к портнихе, чтобы подшить.','','B2','',264),
('w:cotonete','b2','o cotonete','сущ.','ватная палочка','Não uses cotonetes para limpar o interior do ouvido.','Не чисти ватными палочками внутри уха.','','B2','',265),
('w:couve-flor','b2','a couve-flor','сущ.','цветная капуста','Fiz couve-flor no forno com queijo e pão ralado.','Я запекла цветную капусту с сыром и панировкой.','Мн. ч. — couves-flores','B2','',266),
('w:cravo','b2','o cravo','сущ.','гвоздика (цветок и пряность)','O arroz doce leva canela e um pouco de cravo.','В рисовый пудинг кладут корицу и немного гвоздики.','Так же называют клавесин и чёрную точку на коже','B2','',267),
('w:cremoso','b2','cremoso','прил.','нежный, кремовый','Este queijo é muito cremoso e sabe bem com mel.','Этот сыр очень нежный и хорош с мёдом.','','B2','',268),
('w:crítica','b2','a crítica','сущ.','критика, рецензия','O filme teve boas críticas nos jornais portugueses.','Фильм получил хорошие рецензии в португальских газетах.','','B2','',269),
('w:criticar','b2','criticar','глаг.','критиковать','É fácil criticar quem trabalha, difícil é ajudar.','Легко критиковать того, кто работает, а помочь трудно.','','B2','',270),
('w:crítico','b2','crítico','прил.','критический, решающий','O doente esteve em estado crítico durante a noite.','Больной всю ночь был в критическом состоянии.','Как существительное — критик: o crítico de cinema','B2','',271),
('w:croissant','b2','o croissant','сущ.','круассан','Ao pequeno-almoço come sempre um croissant com café.','На завтрак он всегда ест круассан с кофе.','Croissant misto — с ветчиной и сыром, обычный заказ в кафе','B2','',272),
('w:cru','b2','cru','прил.','сырой, необработанный','Prefiro os legumes crus, com um pouco de azeite.','Я больше люблю сырые овощи, слегка политые оливковым маслом.','Ж. р. crua, мн. ч. crus и cruas','B2','',273),
('w:curiosamente','b2','curiosamente','нареч.','любопытно, что интересно','Curiosamente, ninguém reparou na troca dos quadros.','Любопытно, что подмену картин никто не заметил.','Ставится в начале фразы, как вводное слово','B2','',274),
('w:declarar','b2','declarar','глаг.','заявлять, декларировать','Tem de declarar os rendimentos até ao fim de junho.','Доходы нужно задекларировать до конца июня.','','B2','',275),
('w:decorrer','b2','decorrer','глаг.','проходить, протекать','A festa decorreu sem problemas até de madrugada.','Праздник прошёл без происшествий до самого рассвета.','no decorrer de — в течение, по ходу чего-либо','B2','',276),
('w:decreto','b2','o decreto','сущ.','указ, постановление','O novo decreto entra em vigor no próximo mês.','Новое постановление вступает в силу в следующем месяце.','Decreto-lei — обычная форма португальских законов','B2','',277),
('w:dedicar-se','b2','dedicar-se','глаг.','посвящать себя, заниматься','Depois da reforma, dedicou-se inteiramente ao jardim.','Выйдя на пенсию, он полностью посвятил себя саду.','Требует предлога a: dedicar-se à música','B2','',278),
('w:deduzir','b2','deduzir','глаг.','заключать, делать вывод','Pelo silêncio dela, deduzi que algo tinha corrido mal.','По её молчанию я понял, что что-то пошло не так.','Второе значение — вычесть сумму: deduzir no IRS','B2','',279),
('w:deficiência','b2','a deficiência','сущ.','инвалидность; нехватка','O prédio tem acessos para pessoas com deficiência.','В здании есть доступ для людей с инвалидностью.','«Pessoa com deficiência» — принятая нейтральная формула','B2','',280),
('w:degustação','b2','a degustação','сущ.','дегустация','A visita à adega termina com uma degustação de vinhos.','Экскурсия по винодельне заканчивается дегустацией вин.','','B2','',281),
('w:demitir','b2','demitir','глаг.','увольнять, отправлять в отставку','O ministro foi demitido depois do escândalo.','Министра отправили в отставку после скандала.','demitir-se — уйти самому; уволить с работы — despedir','B2','',282),
('w:denso','b2','denso','прил.','густой, плотный','O nevoeiro estava tão denso que ninguém via a estrada.','Туман был такой густой, что дороги никто не видел.','','B2','',283),
('w:dependência','b2','a dependência','сущ.','зависимость','A dependência do telemóvel afeta cada vez mais jovens.','Зависимость от телефона затрагивает всё больше молодых людей.','','B2','',284),
('w:desanimado','b2','desanimado','прил.','унылый, подавленный','Ficou desanimado depois de falhar o exame outra vez.','Он совсем сник, снова провалив экзамен.','','B2','',285),
('w:desapertar','b2','desapertar','глаг.','расстёгивать, ослаблять','Desapertou o cinto e a gravata mal chegou a casa.','Едва придя домой, он расстегнул ремень и галстук.','Обратное — apertar: застегнуть, затянуть','B2','',286),
('w:desativar','b2','desativar','глаг.','отключать, деактивировать','Desativei as notificações para conseguir trabalhar em paz.','Я отключил уведомления, чтобы спокойно работать.','','B2','',287),
('w:desbloquear','b2','desbloquear','глаг.','разблокировать','Fui ao banco desbloquear o cartão multibanco.','Я сходил в банк разблокировать банковскую карту.','','B2','',288),
('w:descalço','b2','descalço','прил.','босой','As crianças andavam descalças na areia da praia.','Дети бегали босиком по песку на пляже.','','B2','',289),
('w:descarado','b2','descarado','прил.','наглый, бесстыжий','Foi descarado o suficiente para pedir mais dinheiro.','У него хватило наглости попросить ещё денег.','Разговорное; и о человеке, и о поступке','B2','',290),
('w:descartar','b2','descartar','глаг.','исключать, отбрасывать','A polícia não descarta a hipótese de um acidente.','Полиция не исключает версию несчастного случая.','','B2','',291),
('w:desconfiar','b2','desconfiar','глаг.','подозревать, не доверять','Desconfio das promessas que parecem boas demais.','Я не доверяю обещаниям, которые звучат слишком хорошо.','Требует de: desconfiar de alguém','B2','',292),
('w:desculpar-se','b2','desculpar-se','глаг.','извиняться','Desculpou-se pelo atraso e sentou-se em silêncio.','Он извинился за опоздание и молча сел.','Извиняться за что-то — desculpar-se por','B2','',293),
('w:desembarcar','b2','desembarcar','глаг.','сходить на берег, высаживаться','Os passageiros desembarcaram logo após a chegada do barco.','Пассажиры сошли на берег сразу после прибытия судна.','','B2','',294),
('w:desemprego','b2','o desemprego','сущ.','безработица','O desemprego desceu para o valor mais baixo dos últimos anos.','Безработица упала до самого низкого уровня за последние годы.','Estar no desemprego — сидеть без работы','B2','',295),
('w:desesperar','b2','desesperar','глаг.','отчаиваться','Não desesperes, ainda há tempo para resolver isto.','Не отчаивайся, ещё есть время всё уладить.','','B2','',296),
('w:desgaste','b2','o desgaste','сущ.','износ; изматывание','O desgaste dos pneus obrigou-nos a trocá-los cedo.','Из-за износа шин пришлось поменять их раньше срока.','И о людях: desgaste emocional — душевная усталость','B2','',297),
('w:desigual','b2','desigual','прил.','неравный, неравномерный','A repartição do trabalho em casa continua desigual.','Домашние дела по-прежнему распределены неравномерно.','','B2','',298),
('w:deslocar-se','b2','deslocar-se','глаг.','передвигаться, ездить','Desloca-se de comboio para o trabalho todos os dias.','Он каждый день ездит на работу на поезде.','Обычное слово в объявлениях и документах','B2','',299),
('w:desmaio','b2','o desmaio','сущ.','обморок','O calor provocou vários desmaios durante o concerto.','Из-за жары на концерте несколько человек потеряли сознание.','','B2','',300),
('w:desmarcar','b2','desmarcar','глаг.','отменять (запись, встречу)','Tive de desmarcar a consulta no dentista.','Мне пришлось отменить запись к стоматологу.','Обратное — marcar: записаться, назначить','B2','',301),
('w:desobediente','b2','desobediente','прил.','непослушный','O cão é simpático, mas muito desobediente com estranhos.','Пёс дружелюбный, но с чужими совсем не слушается.','','B2','',302),
('w:desperdício','b2','o desperdício','сущ.','расточительство; отходы','O desperdício de comida nos restaurantes ainda é enorme.','Пищевых отходов в ресторанах по-прежнему огромное количество.','Que desperdício! — какая расточительность!','B2','',303),
('w:despertar','b2','despertar','глаг.','будить, пробуждать','O cheiro a café despertou-me antes do costume.','Запах кофе разбудил меня раньше обычного.','Также о чувствах: despertar interesse, curiosidade','B2','',304),
('w:despoletar','b2','despoletar','глаг.','спровоцировать, дать толчок','A notícia despoletou uma onda de protestos no país.','Новость вызвала волну протестов по всей стране.','Частое слово в португальских новостях','B2','',305),
('w:desportivo','b2','desportivo','прил.','спортивный','Levou um saco desportivo com o equipamento do ginásio.','Он взял спортивную сумку с формой для зала.','','B2','',306),
('w:detalhado','b2','detalhado','прил.','подробный, детальный','Pediram-me um relatório detalhado sobre as despesas.','У меня попросили подробный отчёт о расходах.','','B2','',307),
('w:determinação','b2','a determinação','сущ.','решимость, упорство','Enfrentou a doença com uma determinação impressionante.','Она встретила болезнь с поразительной стойкостью.','Второе значение — распоряжение, предписание','B2','',308),
('w:devorar','b2','devorar','глаг.','пожирать, проглатывать','Devorou o livro em duas noites, sem dormir quase nada.','Он проглотил книгу за две ночи, почти не поспав.','','B2','',309),
('w:diagnosticar','b2','diagnosticar','глаг.','ставить диагноз','Diagnosticaram-lhe uma alergia ao pó da casa.','Ему поставили диагноз: аллергия на домашнюю пыль.','','B2','',310),
('w:dificultar','b2','dificultar','глаг.','затруднять, усложнять','A chuva dificultou muito o trabalho dos bombeiros.','Дождь сильно затруднил работу пожарных.','','B2','',311),
('w:digestão','b2','a digestão','сущ.','пищеварение','Um chá de erva-cidreira ajuda na digestão.','Чай с мелиссой помогает пищеварению.','','B2','',312),
('w:disjuntor','b2','o disjuntor','сущ.','автомат в электрощитке','Foi abaixo a luz e tive de levantar o disjuntor.','Свет вырубило, и мне пришлось поднять автомат.','Сам щиток — o quadro elétrico','B2','',313),
('w:dispendioso','b2','dispendioso','прил.','дорогостоящий, затратный','Arranjar o carro seria demasiado dispendioso para nós.','Ремонт машины обошёлся бы нам слишком дорого.','','B2','',314),
('w:dispensar','b2','dispensar','глаг.','обходиться без; освобождать','Dispenso o café à noite, senão não durmo.','От кофе вечером я отказываюсь, иначе не усну.','Второе значение — dispensar alguém das aulas','B2','',315),
('w:distinção','b2','a distinção','сущ.','различие, разграничение','Fez a distinção entre o que é urgente e importante.','Он провёл различие между срочным и важным.','','B2','',316),
('w:distribuir','b2','distribuir','глаг.','раздавать, распределять','A professora distribuiu os testes pelos alunos.','Учительница раздала тесты ученикам.','','B2','',317),
('w:diversidade','b2','a diversidade','сущ.','разнообразие','A diversidade de peixe no mercado surpreende os turistas.','Разнообразие рыбы на рынке удивляет туристов.','','B2','',318),
('w:divulgar','b2','divulgar','глаг.','обнародовать, распространять','Os resultados só serão divulgados na próxima semana.','Результаты объявят только на следующей неделе.','','B2','',319),
('w:dobragem','b2','a dobragem','сущ.','дубляж','Em Portugal só os filmes infantis têm dobragem.','В Португалии дублируют только детские фильмы.','Остальное идёт с субтитрами — com legendas','B2','',320),
('w:dramático','b2','dramático','прил.','драматичный, драматический','A situação nos hospitais tornou-se dramática este inverno.','Этой зимой положение в больницах стало драматичным.','','B2','',321),
('w:drástico','b2','drástico','прил.','резкий, радикальный','O governo tomou medidas drásticas para poupar água.','Правительство приняло радикальные меры ради экономии воды.','','B2','',322),
('w:drogaria','b2','a drogaria','сущ.','хозяйственный магазин','Comprei lixívia e esfregonas na drogaria da esquina.','Я купил отбеливатель и швабры в хозяйственном за углом.','Продаёт бытовую химию, а не лекарства — те в farmácia','B2','',323),
('w:duplicado','b2','o duplicado','сущ.','дубликат, второй экземпляр','Pedi um duplicado da chave para deixar aos vizinhos.','Я заказал дубликат ключа, чтобы оставить соседям.','','B2','',324),
('w:duradouro','b2','duradouro','прил.','долговечный, прочный','Procuro uma solução duradoura, não um remendo.','Мне нужно долговечное решение, а не заплатка.','','B2','',325),
('w:educador','b2','o educador','сущ.','воспитатель','A educadora de infância conhece bem cada criança.','Воспитательница в детском саду хорошо знает каждого ребёнка.','Educador de infância — воспитатель детского сада','B2','',326),
('w:efetivamente','b2','efetivamente','нареч.','фактически, в самом деле','Efetivamente, o problema era mais simples do que parecia.','На самом деле задача оказалась проще, чем казалось.','Близко к realmente; частое вводное слово','B2','',327),
('w:eficiência','b2','a eficiência','сущ.','эффективность','A eficiência energética da casa melhorou com as janelas novas.','С новыми окнами энергоэффективность дома выросла.','','B2','',328),
('w:elaborar','b2','elaborar','глаг.','составлять, разрабатывать','A equipa elaborou um plano para os próximos meses.','Команда составила план на ближайшие месяцы.','','B2','',329),
('w:eleição','b2','a eleição','сущ.','выборы','As eleições autárquicas realizam-se de quatro em quatro anos.','Муниципальные выборы проходят раз в четыре года.','По-русски всегда мн. ч., по-португальски бывает и ед.','B2','',330),
('w:embaraçante','b2','embaraçante','прил.','неловкий, конфузный','Foi uma situação embaraçante para toda a família.','Для всей семьи это была неловкая ситуация.','','B2','',331),
('w:embater','b2','embater','глаг.','врезаться, ударяться','O carro embateu no muro à saída da curva.','Машина врезалась в стену на выходе из поворота.','Требует em: embater numa árvore','B2','',332),
('w:embutido','b2','embutido','прил.','встроенный','O quarto tem um armário embutido bastante grande.','В спальне есть довольно большой встроенный шкаф.','Частое слово в объявлениях о жилье','B2','',333),
('w:emitir','b2','emitir','глаг.','выдавать, выписывать','A loja emitiu a fatura com o meu contribuinte.','Магазин выписал счёт с моим налоговым номером.','O contribuinte — налоговый номер, его спрашивают в кассе','B2','',334),
('w:empada','b2','a empada','сущ.','пирожок с начинкой','Comi uma empada de galinha e um café ao balcão.','Я съел пирожок с курицей и выпил кофе у стойки.','','B2','',335),
('w:empreendedor','b2','empreendedor','прил.','предприимчивый','É uma pessoa empreendedora, já abriu três negócios.','Она человек предприимчивый: уже открыла три дела.','Как существительное — предприниматель','B2','',336),
('w:encantar','b2','encantar','глаг.','очаровывать, восхищать','A vista do miradouro encantou toda a gente.','Вид со смотровой площадки восхитил всех.','«Encantado» при знакомстве — «очень приятно»','B2','',337),
('w:encoberto','b2','encoberto','прил.','пасмурный, затянутый облаками','O céu esteve encoberto durante todo o fim de semana.','Все выходные небо было затянуто облаками.','Обычное слово в прогнозе погоды','B2','',338),
('w:encolher','b2','encolher','глаг.','садиться (о ткани), сжиматься','A camisola encolheu na máquina e ficou pequena.','Свитер сел в машинке и стал мал.','Encolher os ombros — пожать плечами','B2','',339),
('w:enérgico','b2','enérgico','прил.','энергичный, решительный','É uma professora enérgica, os miúdos adoram-na.','Учительница энергичная, дети её обожают.','','B2','',340),
('w:enervar','b2','enervar','глаг.','раздражать, нервировать','O trânsito de manhã enerva-me como poucas coisas.','Утренние пробки раздражают меня как мало что ещё.','Estar enervado — быть на нервах, злиться','B2','',341),
('w:enfadonho','b2','enfadonho','прил.','нудный, скучный','A palestra foi longa e bastante enfadonha.','Лекция была длинной и довольно нудной.','','B2','',342),
('w:enganar-se','b2','enganar-se','глаг.','ошибаться, обознаться','Enganei-me na paragem e saí uma antes.','Я перепутал остановку и вышел на одну раньше.','Enganar alguém — обмануть; enganar-se — ошибиться','B2','',343),
('w:engasgar-se','b2','engasgar-se','глаг.','поперхнуться, подавиться','Engasguei-me com uma espinha do peixe ao jantar.','За ужином я подавился рыбной костью.','','B2','',344),
('w:engomar','b2','engomar','глаг.','гладить утюгом','Ainda tenho de engomar as camisas para amanhã.','Мне ещё надо погладить рубашки на завтра.','В Португалии обычнее, чем passar a ferro','B2','',345),
('w:enjoar','b2','enjoar','глаг.','укачивать, тошнить','Enjoo sempre nas curvas da estrada da serra.','Меня всегда укачивает на поворотах горной дороги.','Второе значение — приесться: já enjoei deste prato','B2','',346),
('w:enlatado','b2','enlatado','прил.','консервированный','Prefiro atum enlatado ao atum fresco, sai mais barato.','Консервированный тунец я предпочитаю свежему: выходит дешевле.','','B2','',347),
('w:enrascada','b2','a enrascada','сущ.','передряга, неприятность','Meteu-se numa enrascada por assinar aquele contrato.','Он вляпался в неприятность, подписав тот договор.','Разговорное; meter-se numa enrascada — влипнуть','B2','',348),
('w:enriquecer','b2','enriquecer','глаг.','обогащать, обогащаться','Viver noutro país enriquece mais do que qualquer curso.','Жизнь в другой стране обогащает больше любых курсов.','','B2','',349),
('w:enteado','b2','o enteado','сущ.','пасынок','O enteado dela já é mais alto do que o pai.','Её пасынок уже выше отца.','Падчерица — a enteada, отчим — o padrasto','B2','',350),
('w:entornar','b2','entornar','глаг.','пролить, опрокинуть','Entornei o copo de vinho na toalha branca.','Я пролил бокал вина на белую скатерть.','','B2','',351),
('w:entorse','b2','a entorse','сущ.','растяжение связок','Torci o pé no jogo e fiquei com uma entorse.','Я подвернул ногу на матче и растянул связки.','','B2','',352),
('w:entretido','b2','entretido','прил.','увлечённый, занятый чем-то','Estava tão entretido no livro que nem ouvi a campainha.','Я так увлёкся книгой, что даже не услышал звонка.','Estar entretido com algo — быть чем-то занятым','B2','',353),
('w:entupido','b2','entupido','прил.','засорённый; заложенный','O lava-loiça está entupido desde ontem à noite.','Кухонная раковина забита со вчерашнего вечера.','И о носе: estou com o nariz entupido','B2','',354),
('w:equilibrado','b2','equilibrado','прил.','сбалансированный, уравновешенный','Uma alimentação equilibrada evita muitos problemas de saúde.','Сбалансированное питание избавляет от многих проблем со здоровьем.','','B2','',355),
('w:equívoco','b2','o equívoco','сущ.','недоразумение','Foi tudo um equívoco: afinal a culpa não era dele.','Всё оказалось недоразумением: виноват был вовсе не он.','','B2','',356),
('w:escalão','b2','o escalão','сущ.','разряд, категория','O apoio depende do escalão de rendimento da família.','Пособие зависит от категории дохода семьи.','Escalão etário — возрастная группа','B2','',357),
('w:escaldar','b2','escaldar','глаг.','ошпаривать, обдавать кипятком','Escalda os tomates para tirar a pele com facilidade.','Обдай помидоры кипятком, чтобы легко снять кожицу.','«Está a escaldar» — обжигающе горячо','B2','',358),
('w:escorrer','b2','escorrer','глаг.','стекать, сливать воду','Escorre bem a massa antes de juntar o molho.','Хорошо слей воду с макарон, прежде чем добавить соус.','','B2','',359),
('w:escultura','b2','a escultura','сущ.','скульптура','Há uma escultura de bronze no meio da praça.','Посреди площади стоит бронзовая скульптура.','','B2','',360),
('w:esfregão','b2','o esfregão','сущ.','губка для мытья посуды','O esfregão está velho, compra outro na drogaria.','Губка старая, купи другую в хозяйственном.','Швабра — a esfregona, слово похожее','B2','',361),
('w:esmagador','b2','esmagador','прил.','подавляющий, сокрушительный','A proposta passou com uma maioria esmagadora.','Предложение прошло подавляющим большинством.','','B2','',362),
('w:esmalte','b2','o esmalte','сущ.','лак для ногтей; эмаль','Pintou as unhas com esmalte vermelho para a festa.','Она накрасила ногти красным лаком к празднику.','Также эмаль зубов: o esmalte dos dentes','B2','',363),
('w:espaçoso','b2','espaçoso','прил.','просторный','A casa é antiga, mas espaçosa e muito luminosa.','Дом старый, но просторный и очень светлый.','','B2','',364),
('w:espantar','b2','espantar','глаг.','удивлять, поражать','Espantou-me a rapidez com que resolveram o problema.','Меня поразило, как быстро они решили проблему.','«Não é de espantar» — неудивительно','B2','',365),
('w:especiaria','b2','a especiaria','сущ.','пряность, специя','Os portugueses trouxeram especiarias do Oriente para a Europa.','Португальцы привозили пряности с Востока в Европу.','','B2','',366),
('w:espetada','b2','a espetada','сущ.','шашлык','Comemos uma espetada de carne com batata frita.','Мы съели мясной шашлык с картошкой фри.','Espetada madeirense — на лавровом вертеле, с Мадейры','B2','',367),
('w:espinafre','b2','o espinafre','сущ.','шпинат','Fiz uma quiche de espinafres e queijo da ilha.','Я приготовил киш со шпинатом и островным сыром.','Обычно во мн. ч.: espinafres','B2','',368),
('w:espirro','b2','o espirro','сущ.','чихание, чих','Um espirro tão alto assustou o gato.','От такого громкого чиха кот перепугался.','Чихать — espirrar; «Santinho!» — «будь здоров!»','B2','',369),
('w:espontâneo','b2','espontâneo','прил.','спонтанный, непринуждённый','A reação dela foi espontânea e sincera.','Её реакция была спонтанной и искренней.','','B2','',370),
('w:espumante','b2','espumante','прил.','игристый','Abrimos uma garrafa de vinho espumante à meia-noite.','В полночь мы открыли бутылку игристого вина.','Как существительное — само игристое вино','B2','',371),
('w:estatística','b2','a estatística','сущ.','статистика','As estatísticas mostram uma subida dos preços da habitação.','Статистика показывает рост цен на жильё.','','B2','',372),
('w:estatuto','b2','o estatuto','сущ.','статус; устав','Pediu o estatuto de residente não habitual.','Он подал на статус нерегулярного резидента.','Также устав организации: os estatutos da associação','B2','',373),
('w:estereótipo','b2','o estereótipo','сущ.','стереотип','O filme repete todos os estereótipos sobre o país.','Фильм повторяет все стереотипы об этой стране.','','B2','',374),
('w:estrelado','b2','estrelado','прил.','жареный (о яйце); звёздный','Ao pequeno-almoço come dois ovos estrelados com pão.','На завтрак он ест два жареных яйца с хлебом.','Céu estrelado — звёздное небо, второе значение','B2','',375),
('w:estufado','b2','estufado','прил.','тушёный','A carne estufada fica mais macia com vinho tinto.','Тушёное мясо становится мягче с красным вином.','','B2','',376),
('w:excecional','b2','excecional','прил.','исключительный','Foi um ano excecional para os vinhos do Douro.','Для вин Дору это был исключительный год.','Пишется без p — это европейская норма','B2','',377),
('w:excessivo','b2','excessivo','прил.','чрезмерный','O barulho excessivo à noite dá direito a queixa.','Чрезмерный ночной шум — повод подать жалобу.','','B2','',378),
('w:excluir','b2','excluir','глаг.','исключать, не включать','O preço exclui o pequeno-almoço e o estacionamento.','В цену не входят завтрак и парковка.','','B2','',379),
('w:exibir','b2','exibir','глаг.','показывать, выставлять','O museu exibe uma coleção de azulejos antigos.','В музее выставлена коллекция старинных изразцов.','Exibir-se — рисоваться, красоваться','B2','',380),
('w:expirar','b2','expirar','глаг.','истекать (о сроке)','O prazo para entregar os documentos expira sexta-feira.','Срок подачи документов истекает в пятницу.','Второе значение — выдыхать, в медицине','B2','',381),
('w:explicador','b2','o explicador','сущ.','репетитор','Arranjámos um explicador de matemática para o miúdo.','Мы нашли сыну репетитора по математике.','Занятие с ним — a explicação, во мн. ч. explicações','B2','',382),
('w:expresso','b2','o expresso','сущ.','эспрессо','Pediu um expresso e um pastel de nata.','Он заказал эспрессо и пирожное с кремом.','В Лиссабоне чаще просят uma bica, в Порту — um cimbalino','B2','',383),
('w:fabricar','b2','fabricar','глаг.','производить, изготавливать','A empresa fabrica calçado numa vila do norte.','Компания производит обувь в городке на севере.','','B2','',384),
('w:falecimento','b2','o falecimento','сущ.','кончина','A empresa fechou no dia do falecimento do fundador.','В день кончины основателя фирма не работала.','Вежливое слово вместо morte; falecer — скончаться','B2','',385),
('w:falir','b2','falir','глаг.','обанкротиться','A livraria acabou por falir depois da pandemia.','Книжный магазин в итоге обанкротился после пандемии.','Банкротство — a falência','B2','',386),
('w:fartar-se','b2','fartar-se','глаг.','уставать от чего-то, пресыщаться','Fartei-me de esperar na fila e vim-me embora.','Мне надоело стоять в очереди, и я ушёл.','Estar farto de — быть сытым по горло чем-то','B2','',387),
('w:fenómeno','b2','o fenómeno','сущ.','явление, феномен','As cheias tornaram-se um fenómeno cada vez mais frequente.','Наводнения стали всё более частым явлением.','Пишется с ó — это европейская норма','B2','',388),
('w:ferir','b2','ferir','глаг.','ранить, задевать','O acidente feriu duas pessoas, felizmente sem gravidade.','В аварии пострадали двое, к счастью, легко.','И о чувствах: ferir os sentimentos de alguém','B2','',389),
('w:fermento','b2','o fermento','сущ.','дрожжи; разрыхлитель','Falta o fermento para o bolo crescer no forno.','Не хватает разрыхлителя, чтобы пирог поднялся в духовке.','Fermento de padeiro — дрожжи, fermento em pó — разрыхлитель','B2','',390),
('w:ferroviário','b2','ferroviário','прил.','железнодорожный','A greve ferroviária deixou milhares de pessoas nas estações.','Забастовка железнодорожников оставила тысячи людей на вокзалах.','','B2','',391),
('w:festivo','b2','festivo','прил.','праздничный','A rua tinha um ambiente festivo por causa das marchas.','На улице царила праздничная атмосфера из-за шествий.','As marchas — июньские шествия в честь святых','B2','',392),
('w:fiador','b2','o fiador','сущ.','поручитель','O senhorio exige um fiador para assinar o contrato.','Хозяин квартиры требует поручителя для подписания договора.','Обычное условие при аренде жилья в Португалии','B2','',393),
('w:filosofia','b2','a filosofia','сущ.','философия','Estudou filosofia antes de mudar para direito.','Он изучал философию, прежде чем перейти на юрфак.','','B2','',394),
('w:filtrar','b2','filtrar','глаг.','фильтровать, отсеивать','O programa filtra as mensagens que parecem publicidade.','Программа отсеивает сообщения, похожие на рекламу.','','B2','',395),
('w:financeiro','b2','financeiro','прил.','финансовый','A situação financeira da empresa melhorou este ano.','Финансовое положение компании в этом году улучшилось.','','B2','',396),
('w:semanalmente','b2','semanalmente','нареч.','еженедельно','O grupo reúne-se semanalmente para conversar em português.','Группа собирается еженедельно, чтобы говорить по-португальски.','','B2','',397),
('w:mencionar','b2','mencionar','глаг.','называть, приводить','Não mencionou o preço nem uma única vez.','Цену он не назвал ни разу.','','B2','A8',398),
('w:alertar','b2','alertar','глаг.','предупреждать об опасности','O médico alertou-a para os riscos do tabaco.','Врач предупредил её об опасности курения.','alertar para — предупредить о чём-то','B2','A8',399)
on conflict (id) do update set deck_id = excluded.deck_id, word = excluded.word,
  pos = excluded.pos, ru = excluded.ru, ex = excluded.ex, exru = excluded.exru,
  note = excluded.note, level = excluded.level, tema = excluded.tema, sort = excluded.sort;

insert into public.pt_words (id, deck_id, word, pos, ru, ex, exru, note, level, tema, sort) values
('w:argumentar','b2','argumentar','глаг.','приводить доводы','Argumentou que o prazo era curto de mais.','Он доказывал, что срок слишком короткий.','','B2','A8',400),
('w:suspeitar','b2','suspeitar','глаг.','держать на подозрении','A polícia suspeita de dois funcionários da empresa.','Полиция подозревает двоих сотрудников компании.','suspeitar de alguém; в быту чаще desconfiar','B2','A8',401),
('w:tencionar','b2','tencionar','глаг.','собираться что-то сделать','Tenciono mudar de emprego ainda este ano.','Я намерен сменить работу ещё в этом году.','Разговорнее — ter a intenção de','B2','A8',402),
('w:recear','b2','recear','глаг.','опасаться','Receio que não haja lugares para toda a gente.','Боюсь, мест хватит не всем.','После recear que — конъюнктив','B2','A8',403),
('w:temer','b2','temer','глаг.','страшиться','Os moradores temem que as obras durem anos.','Жильцы боятся, что стройка растянется на годы.','Книжнее, чем ter medo de','B2','A8',404),
('w:temperamento','b2','o temperamento','сущ.','нрав, темперамент','Tem um temperamento calmo, nada o irrita.','Нрав у него спокойный, его ничем не вывести.','','B2','B1',405),
('w:delicadeza','b2','a delicadeza','сущ.','деликатность, тактичность','Teve a delicadeza de avisar antes de aparecer.','Ему хватило такта предупредить, прежде чем прийти.','','B2','B1',406),
('w:grosseria','b2','a grosseria','сущ.','грубость','Respondeu com uma grosseria que deixou todos calados.','Он ответил грубостью, и все замолчали.','','B2','B1',407),
('w:noivado','b2','o noivado','сущ.','помолвка','Anunciaram o noivado num jantar com a família toda.','О помолвке они объявили за ужином со всей семьёй.','Os noivos — жених и невеста, а потом молодожёны','B2','B1',408),
('w:juro','b2','o juro','сущ.','процент по кредиту','Os juros subiram e a prestação ficou mais alta.','Проценты выросли, и платёж стал больше.','Обычно во мн. ч.: os juros','B2','B9',409),
('w:apólice','b2','a apólice','сущ.','страховой полис','A apólice não cobre danos causados por inundação.','Полис не покрывает ущерб от затопления.','','B2','B9',410),
('w:sinistro','b2','o sinistro','сущ.','страховой случай','Participou o sinistro à seguradora no mesmo dia.','О происшествии он сообщил в страховую в тот же день.','Participar um sinistro — заявить о страховом случае','B2','B9',411),
('w:notário','b2','o notário','сущ.','нотариус','Assinámos a escritura no notário na sexta de manhã.','Договор купли-продажи мы подписали у нотариуса в пятницу утром.','','B2','B9',412),
('w:cartório','b2','o cartório','сущ.','нотариальная контора','O cartório fica ao lado do tribunal, na mesma rua.','Нотариальная контора рядом с судом, на той же улице.','','B2','B9',413),
('w:subsídio','b2','o subsídio','сущ.','пособие, доплата','Recebe um subsídio de alimentação todos os meses.','Он каждый месяц получает доплату на питание.','Subsídio de férias e de Natal — две доп. зарплаты в год','B2','B9',414),
('w:reembolso','b2','o reembolso','сущ.','возмещение, возврат денег','O reembolso do bilhete demorou quase um mês.','Возврат денег за билет занял почти месяц.','','B2','B9',415),
('w:requerimento','b2','o requerimento','сущ.','заявление','Entregou o requerimento na câmara na semana passada.','Он подал заявление в мэрию на прошлой неделе.','Requerer — подавать заявление, ходатайствовать','B2','B9',416),
('w:certidão','b2','a certidão','сущ.','свидетельство, справка','Precisa da certidão de nascimento para o processo.','Для дела нужно свидетельство о рождении.','','B2','B9',417),
('w:arrecadação','b2','a arrecadação','сущ.','кладовка, чулан','Cada apartamento tem uma arrecadação na cave.','У каждой квартиры есть кладовка в подвале.','','B2','B2',418),
('w:caução','b2','a caução','сущ.','залог при аренде','A caução é devolvida no fim do arrendamento.','Залог возвращают в конце аренды.','Обычно один-два месяца аренды вперёд','B2','B2',419),
('w:infiltração','b2','a infiltração','сущ.','протечка с улицы','As chuvas provocaram uma infiltração na parede do quarto.','Из-за дождей стену в спальне промочило.','Частая беда в старых домах без изоляции','B2','B2',420),
('w:isolamento','b2','o isolamento','сущ.','утепление, изоляция','O isolamento das janelas fez toda a diferença.','Утепление окон изменило всё.','','B2','B2',421),
('w:corrimão','b2','o corrimão','сущ.','перила','Segura-te ao corrimão, os degraus são altos.','Держись за перила, ступеньки высокие.','','B2','B2',422),
('w:ligadura','b2','a ligadura','сущ.','бинт, повязка','Pôs uma ligadura no tornozelo e continuou a andar.','Он забинтовал лодыжку и пошёл дальше.','Пластырь — o penso rápido','B2','B6',423),
('w:náusea','b2','a náusea','сущ.','тошнота','Sentiu náuseas durante toda a viagem de barco.','Всю дорогу на пароме её тошнило.','Чаще во мн. ч.: ter náuseas','B2','B6',424),
('w:vómito','b2','o vómito','сущ.','рвота','O vómito parou depois do comprimido que lhe deram.','Рвота прекратилась после таблетки, которую ему дали.','Vomitar — рвать, тошнить','B2','B6',425),
('w:inchaço','b2','o inchaço','сущ.','отёк, припухлость','O inchaço do pé baixou com gelo e repouso.','Отёк на ноге спал от льда и покоя.','Inchado — опухший','B2','B6',426),
('w:internar','b2','internar','глаг.','класть в больницу','Foi internado dois dias para ficar em observação.','Его положили в больницу на два дня под наблюдение.','','B2','B6',427),
('w:colesterol','b2','o colesterol','сущ.','холестерин','O médico disse que o colesterol está um pouco alto.','Врач сказал, что холестерин немного повышен.','','B2','B6',428),
('w:escala','b2','a escala','сущ.','пересадка в пути','O voo faz escala em Madrid durante duas horas.','У рейса пересадка в Мадриде на два часа.','Voo direto — прямой рейс, без пересадки','B2','B5',429),
('w:berma','b2','a berma','сущ.','обочина','Encostou o carro à berma para mudar o pneu.','Он съехал на обочину, чтобы поменять колесо.','','B2','B5',430),
('w:reboque','b2','o reboque','сущ.','эвакуатор; буксир','Chamaram o reboque porque o carro não pegava.','Вызвали эвакуатор, потому что машина не заводилась.','Levar a reboque — тащить на буксире','B2','B5',431),
('w:parquímetro','b2','o parquímetro','сущ.','паркомат','Põe moedas no parquímetro, senão levas multa.','Брось монеты в паркомат, иначе получишь штраф.','','B2','B5',432),
('w:lotação','b2','a lotação','сущ.','вместимость','A sala esgotou, a lotação era de trezentos lugares.','Зал был полон: вместимость — триста мест.','«Lotação esgotada» — мест нет, всё продано','B2','B5',433),
('w:granizo','b2','o granizo','сущ.','град','O granizo estragou as vinhas em poucos minutos.','Град за считаные минуты побил виноградники.','','B2','B2',434),
('w:geada','b2','a geada','сущ.','заморозки, иней','Houve geada de manhã e os carros ficaram brancos.','Утром были заморозки, и машины побелели.','','B2','B2',435),
('w:orvalho','b2','o orvalho','сущ.','роса','A relva estava cheia de orvalho ao nascer do sol.','На рассвете трава была вся в росе.','','B2','B2',436),
('w:aguaceiro','b2','o aguaceiro','сущ.','короткий ливень','Apanhámos um aguaceiro à saída do supermercado.','На выходе из супермаркета нас накрыл ливень.','В прогнозе — aguaceiros, короткие дожди','B2','B2',437),
('w:temporal','b2','o temporal','сущ.','буря, непогода','O temporal derrubou árvores em várias ruas da cidade.','Буря повалила деревья на нескольких улицах города.','','B2','B2',438),
('w:vendaval','b2','o vendaval','сущ.','ураганный ветер','O vendaval arrancou o estore da varanda.','Ураганный ветер сорвал рольставню с балкона.','','B2','B2',439),
('w:rajada','b2','a rajada','сущ.','порыв ветра','As rajadas chegaram aos noventa quilómetros por hora.','Порывы ветра доходили до девяноста километров в час.','','B2','B2',440),
('w:pinhal','b2','o pinhal','сущ.','сосновый лес','O caminho para a praia atravessa um pinhal grande.','Дорога к пляжу идёт через большой сосновый лес.','','B2','B2',441),
('w:sobreiro','b2','o sobreiro','сущ.','пробковый дуб','Os sobreiros do Alentejo dão a cortiça das rolhas.','Из пробковых дубов Алентежу делают пробку для бутылок.','Дерево-символ Португалии, рубить его нельзя','B2','B2',442),
('w:ribeira','b2','a ribeira','сущ.','речка, ручей','A ribeira seca todos os verões e volta no outono.','Ручей пересыхает каждое лето и возвращается осенью.','Так же называют набережную в Порту — a Ribeira','B2','B2',443),
('w:nascente','b2','a nascente','сущ.','источник, родник','A água da nascente é fresca mesmo no verão.','Вода из родника прохладная даже летом.','','B2','B2',444),
('w:despedimento','b2','o despedimento','сущ.','увольнение','O despedimento apanhou toda a equipa de surpresa.','Увольнение застало всю команду врасплох.','Despedir — уволить, despedir-se — попрощаться','B2','B1',445),
('w:chefia','b2','a chefia','сущ.','руководство, начальство','A chefia ainda não respondeu ao nosso pedido.','Начальство пока не ответило на нашу просьбу.','','B2','B1',446),
('w:desempenho','b2','o desempenho','сущ.','результативность, показатели','O desempenho da equipa melhorou muito neste trimestre.','Показатели команды в этом квартале заметно выросли.','','B2','B1',447),
('w:propina','b2','a propina','сущ.','плата за обучение','As propinas da universidade pagam-se em dez prestações.','Плату за университет вносят десятью частями.','','B2','B1',448),
('w:afazeres','b2','os afazeres','сущ.','хлопоты, дела','Passou a manhã toda com afazeres domésticos.','Всё утро у неё ушло на домашние хлопоты.','Только во мн. ч.','B2','B3',449),
('w:romaria','b2','a romaria','сущ.','престольный праздник','A romaria da aldeia junta gente de toda a região.','На деревенский праздник съезжаются со всей округи.','Церковный праздник с процессией, музыкой и едой','B2','B4',450),
('w:arraial','b2','o arraial','сущ.','народное гулянье','No arraial havia sardinhas assadas e música até tarde.','На гулянье были жареные сардины и музыка допоздна.','Июньские arraiais — главные праздники Лиссабона','B2','B4',451),
('w:acampamento','b2','o acampamento','сущ.','лагерь, стоянка','Montámos o acampamento junto ao rio antes de escurecer.','Мы разбили лагерь у реки до темноты.','','B2','B4',452),
('w:guisado','b2','o guisado','сущ.','рагу','O guisado de vitela leva batata e cenoura.','В рагу из телятины кладут картошку и морковь.','Guisar — тушить в соусе, близко к estufar','B2','B8',453),
('w:inadequado','b2','inadequado','прил.','неподходящий','O tom da mensagem era inadequado para um cliente.','Тон сообщения для клиента был неуместным.','','B2','A7',454),
('w:terço','b2','o terço','сущ.','треть','Um terço dos alunos faltou por causa da gripe.','Треть учеников не пришла из-за гриппа.','','B2','A5',455),
('w:triplo','b2','o triplo','сущ.','втрое больше','Vendeu o terreno pelo triplo do que pagou.','Он продал участок втрое дороже, чем купил.','','B2','A5',456),
('w:minoria','b2','a minoria','сущ.','меньшинство','Só uma minoria dos presentes se opôs à proposta.','Против предложения выступило лишь меньшинство присутствующих.','','B2','A5',457),
('w:montante','b2','o montante','сущ.','сумма к оплате','O montante total aparece no fim da fatura.','Итоговая сумма указана в конце счёта.','','B2','A5',458),
('w:escassez','b2','a escassez','сущ.','нехватка','Há escassez de médicos de família em muitas zonas.','Во многих районах не хватает семейных врачей.','','B2','A5',459),
('w:abundância','b2','a abundância','сущ.','изобилие','Naquele ano houve abundância de azeitona no Alentejo.','В тот год в Алентежу был обильный урожай оливок.','','B2','A5',460),
('w:subtrair','b2','subtrair','глаг.','вычитать','Subtrai o desconto e paga só o que resta.','Вычти скидку и заплати только остаток.','','B2','A5',461),
('w:raso','b2','raso','прил.','мелкий, неглубокий','A piscina é rasa deste lado, dá para as crianças.','С этой стороны бассейн мелкий, детям подходит.','Colher rasa — ложка без горки','B2','A3',462),
('w:oval','b2','oval','прил.','овальный','A mesa oval da sala levava dez pessoas.','Овальный стол в гостиной вмещал десять человек.','','B2','A3',463),
('w:curvo','b2','curvo','прил.','изогнутый','O caminho curvo dá mais volta, mas é bonito.','Извилистая дорога длиннее, зато красивая.','A curva — поворот дороги','B2','A3',464),
('w:áspero','b2','áspero','прил.','шершавый','A toalha estava áspera de tanto ser lavada.','Полотенце стало жёстким от частых стирок.','','B2','A3',465),
('w:pontiagudo','b2','pontiagudo','прил.','заострённый','Guarda essa faca pontiaguda longe das crianças.','Убери этот острый нож подальше от детей.','Об острие, не о вкусе: острый на вкус — picante','B2','A3',466),
('w:espesso','b2','espesso','прил.','вязкий, тягучий','O molho ficou espesso de mais, junta um pouco de água.','Соус вышел слишком густым, добавь немного воды.','','B2','A3',467),
('w:contorno','b2','o contorno','сущ.','очертание, контур','Via-se o contorno da serra através do nevoeiro.','Сквозь туман виднелись очертания гор.','','B2','A3',468),
('w:ocorrer','b2','ocorrer','глаг.','происходить, случаться','O acidente ocorreu ao início da manhã de domingo.','Авария произошла ранним воскресным утром.','Ocorre-me que… — мне приходит в голову, что…','B2','A1',469),
('w:permanecer','b2','permanecer','глаг.','оставаться, сохраняться','O museu permanece fechado até ao fim das obras.','Музей остаётся закрытым до конца ремонта.','Формальнее, чем ficar','B2','A1',470),
('w:consistir','b2','consistir','глаг.','состоять из','O trabalho consiste em atender e registar pedidos.','Работа состоит в приёме и оформлении заявок.','consistir em — требует em','B2','A1',471),
('w:circunstância','b2','a circunstância','сущ.','обстоятельство','Nestas circunstâncias, é melhor adiar a viagem.','При таких обстоятельствах поездку лучше отложить.','','B2','A1',472),
('w:extremo','b2','o extremo','сущ.','крайность, самый край','A casa fica no extremo norte da aldeia.','Дом стоит на самом северном краю деревни.','','B2','A2',473),
('w:profundidade','b2','a profundidade','сущ.','глубина','A piscina tem dois metros de profundidade ao fundo.','В глубокой части бассейна два метра.','','B2','A2',474),
('w:horizonte','b2','o horizonte','сущ.','горизонт','O sol desapareceu no horizonte por volta das nove.','Солнце скрылось за горизонтом около девяти.','','B2','A2',475),
('w:atalho','b2','o atalho','сущ.','короткая дорога','Conhece um atalho que poupa dez minutos de viagem.','Он знает короткую дорогу, экономящую десять минут.','','B2','A2',476),
('w:borda','b2','a borda','сущ.','край, кромка','Deixou o copo na borda da mesa e caiu.','Он оставил стакан на краю стола, и тот упал.','','B2','A2',477),
('w:superfície','b2','a superfície','сущ.','поверхность','Limpa bem a superfície antes de pintar a parede.','Хорошо очисти поверхность, прежде чем красить стену.','','B2','A2',478),
('w:rodear','b2','rodear','глаг.','опоясывать, идти вокруг','Um muro alto rodeia toda a propriedade.','Всю усадьбу окружает высокая стена.','','B2','A2',479),
('w:percorrer','b2','percorrer','глаг.','проходить, объезжать','Percorremos a costa toda de carro em três dias.','Всё побережье мы объехали на машине за три дня.','','B2','A2',480),
('w:localizar','b2','localizar','глаг.','определять место','A aplicação localiza o autocarro em tempo real.','Приложение показывает, где автобус, в реальном времени.','Localizar-se — находиться где-то','B2','A2',481),
('w:amanhecer','b2','o amanhecer','сущ.','рассвет','Saímos ao amanhecer para evitar o calor do dia.','Мы вышли на рассвете, чтобы не попасть под дневную жару.','','B2','A4',482),
('w:anoitecer','b2','o anoitecer','сущ.','сумерки','Ao anoitecer, as andorinhas voltam todas ao ninho.','В сумерках ласточки все возвращаются в гнёзда.','','B2','A4',483),
('w:apressar','b2','apressar','глаг.','торопить','Não me apresses, ainda temos meia hora.','Не торопи меня, у нас ещё полчаса.','Apressar-se — торопиться самому','B2','A4',484),
('w:atempado','b2','atempado','прил.','своевременный','O aviso atempado evitou um problema bem maior.','Своевременное предупреждение предотвратило гораздо большую проблему.','Atempadamente — вовремя, заблаговременно','B2','A4',485),
('w:rígido','b2','rígido','прил.','жёсткий, строгий','As regras do condomínio são rígidas quanto ao barulho.','Правила дома строги в отношении шума.','','B2','A6',486),
('w:opaco','b2','opaco','прил.','непрозрачный, матовый','O vidro da casa de banho é opaco por dentro.','Стекло в ванной изнутри матовое.','','B2','A6',487),
('w:ardente','b2','ardente','прил.','жгучий, пылкий','Falou do projeto com um entusiasmo ardente.','О проекте он говорил с пылким воодушевлением.','Arder — гореть, жечь','B2','A6',488),
('w:contudo','b2','contudo','нареч.','и всё же','O preço é alto; contudo, a qualidade justifica-o.','Цена высокая, и всё же качество её оправдывает.','','B2','A9',489),
('w:conforme','b2','conforme','предл.','согласно, в соответствии с','Preencha o formulário conforme as instruções da página.','Заполните бланк согласно указаниям на странице.','«Conforme» в ответе — «смотря как», «по-разному»','B2','A9',490),
('w:mediante','b2','mediante','предл.','посредством, при условии','O acesso à sala faz-se mediante marcação prévia.','Доступ в зал — по предварительной записи.','Канцелярское слово, часто в объявлениях','B2','A9',491),
('w:perante','b2','perante','предл.','перед лицом чего-то','Perante tantas dúvidas, decidimos adiar a compra.','Перед лицом стольких сомнений мы отложили покупку.','','B2','A9',492),
('w:caso','b2','caso','союз','если, в случае если','Caso não possas vir, avisa-me até quinta.','Если не сможешь прийти, предупреди до четверга.','После caso — конъюнктив: caso possas, caso venha','B2','A9',493),
('w:sequer','b2','sequer','нареч.','хотя бы, даже','Saiu sem sequer dizer adeus a ninguém.','Он ушёл, даже ни с кем не попрощавшись.','Nem sequer — даже не','B2','A9',494),
('w:decerto','b2','decerto','нареч.','наверняка','Decerto já chegaram, o carro está lá fora.','Наверняка они уже приехали, машина стоит снаружи.','','B2','A9',495),
('w:dificilmente','b2','dificilmente','нареч.','вряд ли','Dificilmente conseguimos chegar lá antes do jantar.','Вряд ли мы успеем туда до ужина.','','B2','A9',496)
on conflict (id) do update set deck_id = excluded.deck_id, word = excluded.word,
  pos = excluded.pos, ru = excluded.ru, ex = excluded.ex, exru = excluded.exru,
  note = excluded.note, level = excluded.level, tema = excluded.tema, sort = excluded.sort;

delete from public.pt_words
 where deck_id = 'b2' and updated_at < now();

commit;

select count(*) as слов, count(*) filter (where level = '') as без_уровня,
       count(distinct tema) as тем
  from public.pt_words where deck_id = 'b2';
